#!/usr/bin/env python3
"""Turns the buildings in data/games/*.json into the table the engine indexes
by Building.

The api describes a building per round: its category, how many a village may
hold, how many levels it has, which page of the build menu it sits on and
whether it takes a module. The engine wants one row per building across every
round, so the rows here are the union over the rounds in data/games, newest
first: a round that adds a building adds an enumerator, and a round that drops
one keeps it only while an older round still lists it.

    tools/buildings-to-cpp.py build/buildings.gen.cpp

Written beside it: build/buildings.gen.hpp, the Building and BuildingType
enumerations village.hpp includes.
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).parent.parent
GAMES = HERE / 'data' / 'games'
PLAYERS = HERE / 'data' / 'players'

# Buildings no round's hq/config lists, described here instead. Bare ground and
# the village centre the api reports as the hq are not built from the build
# menu; the obelisk is missing from every round's menu and yet stands in
# villages in data/players, so its row is kept by hand. Each row is the Info
# aggregate's fields after the id.
#                   slots limit maxLevel     tier type      sealable
UNLISTED = {
    'NONE': ('None', 0, 0, '0', 0, 'None', False),
    'VILLAGE_CENTRE': ('VillageCentre', 0, 1, 'MaxLevel', 0, 'None', False),
    'OBELISK': ('Obelisk', 1, 3, 'MaxLevel', 4, 'Support', True),
}

# The api's names, where the enumerator is not the name in CamelCase.
ENUMERATORS = {'WOODCUTTER': 'Hut', 'STORAGE': 'Storehouse'}

# Word-for-word replacements applied while a name is turned into an
# enumerator, for British spelling.
WORDS = {'CENTER': 'Centre'}


def enumerator(name):
    if name in ENUMERATORS:
        return ENUMERATORS[name]
    return ''.join(WORDS.get(word, word.capitalize()) for word in name.split('_'))


def quoted(text):
    return '"' + str(text).replace('\\', '\\\\').replace('"', '\\"') + '"'


def rows():
    """One row per building, and the category ids, both newest round first.

    Where two rounds describe the same building differently, the newest round
    that lists it is taken: what a building is now is what the engine plans
    with.
    """
    files = sorted((f for f in GAMES.glob('*.json') if f.name != 'index.json'),
                   key=lambda f: int(f.stem), reverse=True)
    if not files:
        raise SystemExit(f'no games in {GAMES}; run tools/fetch-games.py --rules')

    seen = {}
    categories = []
    for f in files:
        for b in json.load(f.open())['buildings']:
            for category in b.get('category') or []:
                if category not in categories:
                    categories.append(category)
            if b['name'] not in seen:
                seen[b['name']] = b
    return seen, categories


def built():
    """Every building name standing in a village in data/players.

    The rules a round serves are its build menu, not everything that may
    stand: a village can hold a building no menu offers any more. A name here
    without a row would be a village the engine turns down, so the table is
    checked against these rather than against the menus alone.
    """
    names = set()
    for f in sorted(PLAYERS.glob('*.json')):
        for village in json.load(f.open()):
            names.update(b['name'] for b in village.get('buildings') or [])
    return names


def main():
    if len(sys.argv) != 2:
        raise SystemExit(f'usage: {sys.argv[0]} <output.cpp>')

    listed, categories = rows()
    for name in UNLISTED:
        if name in listed:
            raise SystemExit(f'{name} is both listed by the api and described here as unlisted')

    types = ['NONE'] + categories
    table = [(name, quoted(name)) + fields for name, fields in UNLISTED.items()]
    for name, b in listed.items():
        category = (b.get('category') or [None])[0]
        table.append((
            name, quoted(name), enumerator(name), 1, b.get('maxCount') or 0,
            'MaxLevel' if b.get('upgradeable') else '1', b.get('tiers') or 0,
            enumerator(category) if category else 'None',
            bool(b.get('acceptModules')),
        ))

    missing = sorted(built() - {row[0] for row in table})
    if missing:
        raise SystemExit(f'villages in {PLAYERS} hold buildings no round lists and UNLISTED does not '
                         f'describe: {", ".join(missing)}')

    head = '// Generated by tools/buildings-to-cpp.py from data/games/. Do not edit.'
    header = [
        head,
        '#pragma once',
        '',
        '#include <array>',
        '#include <string_view>',
        '',
        'namespace Factions {',
        '',
        '/* Every building any round in data/games offers, plus the two the api does',
        '   not list: bare ground and the village centre. Each enumerator indexes the',
        '   table in buildings.gen.cpp. */',
        'enum class Building {',
    ]
    header += [f'    {row[2]},' for row in table]
    header += [
        '',
        '    Count // keep last; every enumerator above needs a row in the table',
        '};',
        '',
        "// The api's build-menu categories. A building carries the first of the",
        '// categories the api gives it.',
        'enum class BuildingType {',
    ]
    header += [f'    {enumerator(one)},' for one in types]
    header += [
        '',
        '    Count // keep last; every enumerator above needs an id below',
        '};',
        '',
        'namespace BuildingTypes {',
        f'inline constexpr std::array<std::string_view, {len(types)}> Ids{{',
        '    ' + ', '.join(quoted(one) for one in types),
        '};',
        '} // namespace BuildingTypes',
        '',
        '} // namespace Factions',
    ]

    source = [
        head,
        '#include "village.hpp"',
        '',
        '#include <array>',
        '',
        'namespace Factions {',
        '',
        'namespace Buildings {',
        'namespace {',
        '//                                  slots limit  max        tier type                  seal',
        'constexpr std::array Table{',
    ]
    for _, id_, enum_name, slots, limit, max_level, tier, type_, sealable in table:
        source.append(f'    Info{{Building::{enum_name}, {id_}, {slots}, {limit}, {max_level}, '
                      f'{tier}, BuildingType::{type_}, {str(sealable).lower()}}},')
    source += [
        '};',
        '',
        'static_assert(Table.size() == Enum::Count<Building>, "every Building enumerator needs a row in Table");',
        '',
        'consteval bool rowsAreWellFormed()',
        '{',
        '    for (std::size_t a = 0; a < Table.size(); ++a) {',
        '        const Info& row = Table[a];',
        '',
        '        // A row is indexed by its enumerator, so the two orders must agree.',
        '        if (row.building != static_cast<Building>(a))',
        '            return false;',
        '        if (row.id.empty())',
        '            return false;',
        '        if (row.slots < 0 || row.limit < 0 || row.maxLevel < 0 || row.tier < 0)',
        '            return false;',
        '        // Bare ground carries no level and no seal, which is why sealable()',
        '        // alone answers for a tile as well as for a building.',
        '        if ((row.building == Building::None) != (row.maxLevel == 0))',
        '            return false;',
        '        if (row.building == Building::None && row.sealable)',
        '            return false;',
        '',
        '        for (std::size_t b = a + 1; b < Table.size(); ++b)',
        '            if (row.id == Table[b].id)',
        '                return false;',
        '    }',
        '    return true;',
        '}',
        '',
        'static_assert(rowsAreWellFormed(), "each row must sit at its own enumerator, with a non-empty unique id, non-negative "',
        '                                   "values, and no level or seal on bare ground");',
        '} // namespace',
        '',
        'std::span<const Info> all() { return Table; }',
        '',
        'const Info& of(Building building) { return Table[static_cast<std::size_t>(building)]; }',
        '',
        'std::optional<Building> tryFromId(std::string_view id)',
        '{',
        '    for (const Info& info : Table)',
        '        if (info.id == id)',
        '            return info.building;',
        '    return std::nullopt;',
        '}',
        '',
        '} // namespace Buildings',
        '',
        '} // namespace Factions',
    ]

    out = pathlib.Path(sys.argv[1])
    out.write_text('\n'.join(source) + '\n')
    out.with_suffix('.hpp').write_text('\n'.join(header) + '\n')


if __name__ == '__main__':
    main()
