/* Writes what the page needs to know about the game, from the engine's own
   tables, as a script loaded before app.js. app.js holds only labels, icons
   and colours, and asserts at startup that it has one for every id here. */

#include <cstdio>
#include <format>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>

#include "effects.hpp"
#include "game.hpp"
#include "solver.hpp"
#include "village.hpp"

using namespace Factions;

namespace {

std::string quoted(std::string_view text)
{
    std::string out = "\"";
    for (const char c : text) {
        if (c == '"' || c == '\\')
            out += '\\';
        out += c;
    }
    return out + '"';
}

// Enough digits for JavaScript to read the double back exactly.
std::string quantity(double value)
{
    return std::format("{:.10g}", value);
}

// A list of names, as a JavaScript array of strings.
std::string names(const auto& ids)
{
    std::string out = "[";
    for (const std::string_view id : ids)
        out += (out.size() > 1 ? ", " : "") + quoted(id);
    return out + ']';
}

std::string chars(const auto& letters)
{
    std::string out = "[";
    for (const char c : letters)
        out += (out.size() > 1 ? ", " : "") + quoted(std::string_view{&c, 1});
    return out + ']';
}

void write(std::ostream& to)
{
    to << "'use strict';\n"
       << "/* Generated by tools/schema.cpp from the engine's own tables.\n"
       << "   Do not edit: rebuild instead. */\n\n"
       << "const SCHEMA = {\n";

    to << "  width: " << Village::Width << ",\n"
       << "  height: " << Village::Height << ",\n"
       << "  maxLevel: " << MaxLevel << ",\n\n";

    to << "  // The constants the engine computes with, so the page can display\n"
       << "  // them without keeping a second copy.\n"
       << "  politicsBonus: " << quantity(PoliticsBonus) << ",\n"
       << "  baseMarketTax: " << quantity(BaseMarketTax) << ",\n"
       << "  // What the hq is worth on knight and on guardian power, before\n"
       << "  // any share or factor.\n"
       << "  basePower: " << quantity(BasePower) << ",\n"
       << "  // Added to the buildings' storage before anything scales it.\n"
       << "  baseStorage: { ";
    for (const Resource resource : Enum::values<Resource>())
        to << (resource == Resource{} ? "" : ", ") << Resources::toId(resource) << ": " << quantity(BaseStorage[static_cast<std::size_t>(resource)]);
    to << " },\n"
       << "  masterSealBonus: " << quantity(MasterSealBonus) << ",\n"
       << "  sealBonus: " << quantity(SealBonus) << ",\n"
       << "  // What each season change multiplies every cost multiplier by.\n"
       << "  seasonCostStep: " << quantity(Game::SeasonCostStep) << ",\n\n";

    to << "  terrains: " << names(Terrains::Ids) << ",\n"
       << "  orientations: " << chars(Orientations::Chars) << ",\n"
       << "  seals: " << names(Seals::Ids) << ",\n"
       << "  politics: " << names(PoliticsChoices::Ids) << ",\n"
       << "  buildingTypes: " << names(BuildingTypes::Ids) << ",\n\n";

    to << "  // The terrains that cannot hold a building.\n"
       << "  unbuildable: [";
    {
        std::string out;
        for (const Terrain terrain : Enum::values<Terrain>())
            if (!Terrains::buildable(terrain))
                out += (out.empty() ? "" : ", ") + quoted(Terrains::toId(terrain));
        to << out;
    }
    to << "],\n\n";

    to << "  // The three lists modifier ids are built from, so the page lays its\n"
       << "  // tables out in the order the engine reads them.\n"
       << "  resources: " << names(Resources::Ids) << ",\n"
       << "  rateOrCapacities: " << names(RateOrCapacities::Ids) << ",\n"
       << "  efficiencies: " << names(Efficiencies::Ids) << ",\n"
       << "  efficiencyField: " << quoted(Efficiencies::Field) << ",\n"
       << "  powers: " << names(Powers::Ids) << ",\n"
       << "  powerField: " << quoted(Powers::Field) << ",\n"
       << "  units: " << names(Units::Ids) << ",\n"
       << "  unitField: " << quoted(Units::Field) << ",\n"
       << "  politicsField: " << quoted(PoliticsChoices::Field) << ",\n";

    to << "  modifierSources: [\n";
    for (std::size_t i = 0; i < Enum::Count<ModifierSource>; ++i) {
        const ModifierSource source = static_cast<ModifierSource>(i);
        to << std::format("    {{ id: {}, share: {}, addedBefore: {}, addedAfter: {}, resourceOnly: {} }},\n", quoted(ModifierSources::toId(source)), ModifierSources::isShare(source) ? "true" : "false", ModifierSources::addedBeforeMultiplier(source) ? "true" : "false", ModifierSources::addedAfterMultiplier(source) ? "true" : "false", ModifierSources::resourceOnly(source) ? "true" : "false");
    }
    to << "  ],\n\n";

    /* Which buildings each seal fits, listed only where it does not fit every
       sealable building. The page reads the rule from here. */
    to << "  sealFits: {\n";
    for (std::size_t i = 0; i < Enum::Count<Seal>; ++i) {
        const Seal seal = static_cast<Seal>(i);
        if (seal == Seal::None)
            continue;

        std::string listed;
        bool everySealable = true;
        for (const Buildings::Info& info : Buildings::all()) {
            if (!info.sealable)
                continue;
            if (Buildings::takesSeal(info.building, seal))
                listed += (listed.empty() ? "" : ", ") + quoted(info.id);
            else
                everySealable = false;
        }
        if (everySealable)
            continue; // it fits every sealable building, so there is nothing to list

        to << std::format("    {}: [{}],\n", quoted(Seals::toId(seal)), listed);
    }
    to << "  },\n\n";

    to << "  buildings: [\n";
    for (const Buildings::Info& info : Buildings::all()) {
        to << std::format("    {{ id: {}, slots: {}, limit: {}, maxLevel: {}, tier: {}, type: {}, sealable: {} }},\n", quoted(info.id), info.slots, info.limit, info.maxLevel, info.tier, quoted(BuildingTypes::toId(info.type)), info.sealable ? "true" : "false");
    }
    to << "  ],\n\n";

    to << "  modifiers: [\n";
    for (const ModifierIds::Described& one : ModifierIds::all()) {
        to << std::format("    {{ id: {}, neutral: {}, minimum: {}, addedBefore: {}, addedAfter: {} }},\n", quoted(one.id), quantity(one.neutral), quantity(one.minimum), one.addedBeforeMultiplier ? "true" : "false", one.addedAfterMultiplier ? "true" : "false");
    }
    to << "  ],\n\n";

    /* Every game the engine carries, so the page can offer them, draw the
       right terrain and state what each building produces. These are the same
       effects the engine computes from, so the displayed rules and the
       arithmetic cannot diverge. */
    to << "  games: [\n";
    for (const Game::Config& g : Game::all()) {
        to << std::format("    {{ id: {}, map: {}, ongoing: {}, width: {}, height: {}, marketTax: {}, terrain: ", g.id, quoted(g.map), g.ongoing ? "true" : "false", g.width, g.height, quantity(g.marketTax));

        std::string ground;
        for (const std::string_view t : g.terrain)
            ground += (ground.empty() ? "" : ", ") + quoted(t);
        to << '[' << ground << "], ";

        /* The seasons, and the index of the one the cost multipliers above
           were fetched in. Which season is current is determined on the page,
           which has a clock. */
        std::string listed;
        for (const Game::Season& one : g.seasons)
            listed += std::format("{}{{ name: {}, start: {}, end: {} }}", listed.empty() ? "" : ", ", quoted(one.name), quoted(one.start), quoted(one.end));
        to << std::format("seasons: [{}], seasonNow: {}, shapes: [\n", listed, g.seasonNow);

        // A building's shape, per game: the one property that varies between
        // rounds and so cannot live in the page's own tables.
        for (const Game::Building& b : g.buildings) {
            to << std::format("      {{ building: {}, shape: {} }},\n", quoted(b.name), quoted(Game::name(b.shape)));
        }
        to << "    ], effects: [\n";

        const auto writeEffects = [&to](std::string_view name, std::span<const Game::Effect> effects) {
            for (const Game::Effect& e : effects) {
                std::string on;
                for (const std::string_view one : e.on)
                    on += (on.empty() ? "" : ", ") + quoted(one);

                to << std::format("      {{ building: {}, where: {}, amount: {}, quantity: {}, rateOrCapacity: {},"
                                  " value: {}, perLevel: {}, byCategory: {}, on: [{}] }},\n",
                                  quoted(name), quoted(Game::name(e.where)), quoted(Game::name(e.amount)), quoted(Game::name(e.quantity)), quoted(Game::name(e.rateOrCapacity)), quantity(e.value), e.perLevel ? "true" : "false", e.byCategory ? "true" : "false", on);
            }
        };

        for (const Game::Building& b : g.buildings)
            writeEffects(b.name, b.effects);

        // The centre is in no game's building list; the engine synthesises its effects.
        writeEffects(Buildings::toId(Building::VillageCentre), Rules::of(g.id).effects(Building::VillageCentre));
        to << "    ] },\n";
    }
    to << "  ],\n\n";

    to << "  goals: [\n";
    for (const Objective::Info& info : Objective::all())
        to << std::format("    {{ id: {}, label: {} }},\n", quoted(info.id), quoted(info.label));
    to << "  ],\n";

    to << "};\n";
}

} // namespace

int main(int argc, char** argv)
{
    if (argc != 2) {
        std::cerr << "usage: " << argv[0] << " <output.js>\n";
        return 2;
    }

    std::ofstream out{argv[1]};
    if (!out) {
        std::cerr << "cannot write '" << argv[1] << "'\n";
        return 1;
    }

    write(out);
    return out ? 0 : 1;
}
