'use strict';

/* What the planner and the simulator both need: the tables SCHEMA describes,
   the art and geometry a board is drawn from, and the one wrapper around the
   WebAssembly engine. Both pages load it before their own script.

   SCHEMA is generated by tools/schema.cpp. This file adds only what the engine
   does not define: labels, images, colours. joined() below throws at startup if
   either side declares an id the other does not.

   Nothing here reads a page's own state: the three functions that walk a board
   are given the tiles to walk. */

const WIDTH = SCHEMA.width;
const HEIGHT = SCHEMA.height;
const TILE_COUNT = WIDTH * HEIGHT;
const CENTRE = 'VILLAGE_CENTRE';
const EMPTY = 'NONE';
const MIN_VILLAGE_LEVEL = 1;
const MIN_BUILDING_LEVEL = 1;
const MAX_LEVEL = SCHEMA.maxLevel;

// Merges an engine-supplied row with this file's presentation fields, engine
// first, so nothing here can override a computed value.
function joined(rows, trimmings, what) {
  const listed = rows.map((row) => (typeof row === 'string' ? { id: row } : row));

  const bare = listed.filter((row) => !(row.id in trimmings)).map((row) => row.id);
  if (bare.length) throw new Error(`app.js has no ${what} for: ${bare.join(', ')}`);

  const extra = Object.keys(trimmings).filter((id) => !listed.some((row) => row.id === id));
  if (extra.length) throw new Error(`app.js describes ${what} the engine has never heard of: ${extra.join(', ')}`);

  return listed.map(({ id, ...engine }) => ({ key: id, ...engine, ...trimmings[id] }));
}

const TERRAIN_ATLAS = 'https://www.factions-online.com/map/base_terrains.png';
const ATLAS_COLS = 16;
const ATLAS_CELL = 34;
const ATLAS_PAD = 1;
const ATLAS_ART = 32;
const ATLAS_W = 544;
const ATLAS_H = 1020;

const TERRAINS = joined(SCHEMA.terrains, {
  PLAINS: { name: 'Plains', color: '#8fb254', atlas: null },
  FOREST: { name: 'Forest', color: '#2f6b3c', atlas: 96 },
  MOUNTAIN: { name: 'Mountain', color: '#8a7f70', atlas: 296 },
  HIGH_MOUNTAIN: { name: 'High mountain', color: '#cbd2da', atlas: 384 },
  SEA: { name: 'Sea', color: '#2c6b9e', atlas: 200 },
  SWAMP: { name: 'Swamp', color: '#6a6733', atlas: 192 },
}, 'terrain');

const MASK_TO_LOCAL = {
  0: 0, 4: 1, 68: 2, 64: 3, 16: 4, 28: 5, 124: 6, 112: 7,
  20: 16, 80: 17, 21: 18, 84: 19, 17: 20, 31: 21, 255: 22, 241: 23,
  5: 32, 65: 33, 69: 34, 81: 35, 1: 36, 7: 37, 199: 38, 193: 39,
  23: 48, 209: 49, 116: 50, 92: 51, 247: 52, 223: 53, 213: 54, 87: 55,
  29: 64, 113: 65, 197: 66, 71: 67, 253: 68, 127: 69, 117: 70, 93: 71,
  125: 80, 215: 81, 245: 82, 95: 83, 221: 84, 119: 85, 85: 86,
};

const MASK_SURROUNDED = 255;

function atlasPosition(index) {
  const col = index % ATLAS_COLS;
  const row = Math.floor(index / ATLAS_COLS);
  const x = (ATLAS_PAD + col * ATLAS_CELL) / (ATLAS_W - ATLAS_ART) * 100;
  const y = (ATLAS_PAD + row * ATLAS_CELL) / (ATLAS_H - ATLAS_ART) * 100;
  return `${x}% ${y}%`;
}

function terrainMask(tiles, i) {
  const x = i % WIDTH;
  const y = Math.floor(i / WIDTH);
  const here = tiles[i].terrain;

  const same = (dx, dy) => {
    const cx = x + dx;
    const cy = y + dy;
    if (cx < 0 || cx >= WIDTH || cy < 0 || cy >= HEIGHT) return false;
    return tiles[cy * WIDTH + cx].terrain === here;
  };

  const n = same(0, -1);
  const e = same(1, 0);
  const s = same(0, 1);
  const w = same(-1, 0);

  let mask = 0;
  if (n) mask |= 1;
  if (e) mask |= 4;
  if (s) mask |= 16;
  if (w) mask |= 64;
  if (n && e && same(1, -1)) mask |= 2;
  if (e && s && same(1, 1)) mask |= 8;
  if (s && w && same(-1, 1)) mask |= 32;
  if (w && n && same(-1, -1)) mask |= 128;
  return mask;
}

function applyTerrain(el, key, mask) {
  const terrain = TERRAIN_BY_KEY.get(key);
  el.style.backgroundColor = terrain.color; // shows through until the sheet loads

  if (terrain.atlas === null) {
    el.style.setProperty('--terrain-img', 'NONE');
    el.style.setProperty('--terrain-pos', '0 0');
    return;
  }

  const local = MASK_TO_LOCAL[mask] ?? 0;
  el.style.setProperty('--terrain-img', `url("${TERRAIN_ATLAS}")`);
  el.style.setProperty('--terrain-pos', atlasPosition(terrain.atlas + local));
}

const UNBUILDABLE = new Set(SCHEMA.unbuildable);

const ART = 'https://www.factions-online.com/images/buildings';
const SLOT_ART = 'https://www.factions-online.com/ui';

const BUILDING_TYPES = joined(SCHEMA.buildingTypes, {
  ECONOMY: { name: 'Economy', img: `${SLOT_ART}/slot_economy.svg` },
  MILITARY: { name: 'Military', img: `${SLOT_ART}/slot_military.svg` },
  WORKER: { name: 'Worker', img: `${SLOT_ART}/slot_worker.svg` },
  SUPPORT: { name: 'Support', img: `${SLOT_ART}/slot_support.svg` },
  NONE: { name: 'Untyped', img: `${SLOT_ART}/slot.svg` },
}, 'building type');

const TYPE_BY_KEY = new Map(BUILDING_TYPES.map((t) => [t.key, t]));

/* Slots, limit, level cap, tier and type come from the engine; only the label
   and the image are defined here. Shape is absent: the games disagree on it,
   so it is read per game by readEffects (see shapeOf). */
const BUILDINGS = joined(SCHEMA.buildings, {
  NONE: { name: 'Empty', img: null },
  WOODCUTTER: { name: 'Hut', img: `${ART}/woodcutter.png` },
  MINE: { name: 'Mine', img: `${ART}/mine.png` },
  SAWMILL: { name: 'Sawmill', img: `${ART}/sawmill.png` },
  FURNACE: { name: 'Furnace', img: `${ART}/furnace.png` },
  VILLAGE_CENTRE: { name: 'Village centre', img: `${ART}/town_center_1.png` },
  OBELISK: { name: 'Obelisk', img: `${ART}/obelisk.png` },
  KNIGHT_TRAINING_CENTER: { name: 'Knight training centre', img: `${ART}/knight_training_center.png` },
  GUARDIAN_TRAINING_CENTER: { name: 'Guardian training centre', img: `${ART}/guardian_training_center.png` },
  STORAGE: { name: 'Storehouse', img: `${ART}/storage.png` },
  WAREHOUSE: { name: 'Warehouse', img: `${ART}/warehouse.png` },
  TRAINING_CENTER: { name: 'Training centre', img: `${ART}/training_center.png` },
  TAVERN: { name: 'Tavern', img: `${ART}/tavern.png` },
  HOUSE: { name: 'House', img: `${ART}/house.png` },
  GUARD_TOWER: { name: 'Guard tower', img: `${ART}/guard_tower.png` },
  SHIPYARD: { name: 'Shipyard', img: `${ART}/shipyard.png` },
  RESEARCH_CENTER: { name: 'Research centre', img: `${ART}/research_center.png` },
  BUILDERS_BUREAU: { name: "Builders' bureau", img: `${ART}/builders_bureau.png` },
  MARKET: { name: 'Market', img: `${ART}/market.png` },
  ARENA: { name: 'Arena', img: `${ART}/arena.png` },
  WAR_CAMP: { name: 'War camp', img: `${ART}/war_camp.png` },
  GUILD_HALL: { name: 'Guild hall', img: `${ART}/guild_hall.png` },
  TOWN_HALL: { name: 'Town hall', img: `${ART}/town_hall.png` },
  MERCENARY_OFFICE: { name: 'Mercenary office', img: `${ART}/mercenary_office.png` },
  GARRISON_HALL: { name: 'Garrison hall', img: `${ART}/garrison_hall.png` },
  RECYCLING_WORKSHOP: { name: 'Recycling workshop', img: `${ART}/recycling_workshop.png` },
  ACADEMY: { name: 'Academy', img: `${ART}/academy.png` },
}, 'building');

// The build-menu pages, derived from the buildings themselves.
const TIERS = [...new Set(BUILDINGS.map((b) => b.tier))].filter((t) => t > 0).sort((a, b) => a - b);

const MODULE_ART = 'https://www.factions-online.com/icons/modules';

const NO_SEAL = 'NONE';
const SEALS = joined(SCHEMA.seals, {
  NONE: { name: 'No seal', img: null, note: null },
  LEVEL_BOOST: {
    name: "Master builder's seal",
    img: `${MODULE_ART}/level_boost.png`,
    note: `Effective level <strong>×${SCHEMA.masterSealBonus}</strong>. Flat figures unchanged.`,
  },
  ECONOMIC_BOOST: {
    name: 'Mill seal',
    img: `${MODULE_ART}/economic_boost.png`,
    note: `<strong>+${Math.round((SCHEMA.sealBonus - 1) * 100)}% wood/t and iron/t</strong> on this tile.`,
  },
  STORAGE_EXPANDER: {
    name: 'Barrel seal',
    img: `${MODULE_ART}/storage_expander.png`,
    note: `<strong>+${Math.round((SCHEMA.sealBonus - 1) * 100)}% cap</strong> of every kind on this tile.`,
  },
}, 'seal');

const SEAL_BY_KEY = new Map(SEALS.map((s) => [s.key, s]));

/* Seals the engine restricts to certain buildings, listed by the buildings
   they fit. A seal absent from this map fits every sealable building; only the
   mill is restricted, since it multiplies the wood or iron produced on its own
   tile. */
const SEAL_FITS = new Map(Object.entries(SCHEMA.sealFits).map(([seal, on]) => [seal, new Set(on)]));

function sealable(key) {
  return BUILDING_BY_KEY.get(key)?.sealable === true;
}

function sealFits(seal, building) {
  if (seal === NO_SEAL) return true;
  if (!sealable(building)) return false;
  const only = SEAL_FITS.get(seal);
  return only === undefined || only.has(building);
}
const MASTER_LEVEL_BONUS = SCHEMA.masterSealBonus;
// The factor a mill or barrel applies to the quantity on its own tile.
const SEAL_BONUS = SCHEMA.sealBonus;

const RESOURCES = joined(SCHEMA.resources, {
  wood: { name: 'Wood', cls: 'wood-value' },
  iron: { name: 'Iron', cls: 'iron-value' },
  workers: { name: 'Workers', cls: 'workers-value' },
  soldiers: { name: 'Soldiers', cls: 'soldiers-value' },
}, 'resource');

const GLOBAL_RESOURCES = RESOURCES.map((r) => r.key);

// The two quantities held per resource, and the abbreviations built from them.
const RATE_OR_CAPACITIES = joined(SCHEMA.rateOrCapacities, {
  production: { suffix: '/t', full: 'production' },
  storage: { suffix: ' cap', full: 'storage' },
}, 'rate or capacity');

// the engine's two names, which the ids below are built from
const [RATE, CAPACITY] = SCHEMA.rateOrCapacities;

const RESOURCE_OBJECTIVES = RATE_OR_CAPACITIES.flatMap((m) => RESOURCES.map((r) => ({
  id: `${r.key}.${m.key}`, name: `${r.name}${m.suffix}`, full: `${r.name} ${m.full}`,
})));

// The five world ratings, each a share rather than a resource.
/* `quests`: the api lists the quest multiplier against attack, defence and
   worker but not map or projects, and the engine follows it. */
const EFFICIENCIES = joined(SCHEMA.efficiencies, {
  attack: { name: 'Attack', short: 'atk', soldiers: true, workers: false, quests: true },
  defense: { name: 'Defence', short: 'def', soldiers: true, workers: false, quests: true },
  worker: { name: 'Worker', short: 'wrk', soldiers: false, workers: true, quests: true },
  map: { name: 'Map', short: 'map', soldiers: false, workers: true, quests: false },
  projects: { name: 'Projects', short: 'prj', soldiers: false, workers: true, quests: false },
}, 'efficiency');

/* The military powers, each an absolute figure that starts from the base the
   hq is worth rather than a share. Support power is added to knight and to
   guardian power alike, so it is already in both. */
const POWERS = joined(SCHEMA.powers, {
  support: { name: 'Support power', short: 'sup' },
  knight: { name: 'Knight power', short: 'kni' },
  guardian: { name: 'Guardian power', short: 'gua' },
}, 'power');

const BASE_POWER = SCHEMA.basePower;
const BASE_STORAGE = SCHEMA.baseStorage;

// the perk's name in game; terrainBonusFactor in the api
const FERTILE_GROUNDS = 'Fertile grounds';

// The two the api lists under production beside the resources.
const UNITS = joined(SCHEMA.units, {
  knight: { name: 'Knights', one: 'Knight', short: 'kni' },
  guardian: { name: 'Guardians', one: 'Guardian', short: 'gua' },
}, 'unit');

/* Knight and guardian power and production are four goals the engine accepts
   but two rows on the page: one choice of unit selects the reading of both
   rows. Guardian is first, so it is the reading a fresh page starts on and the
   id under which each row is listed. */
const UNIT_READINGS = ['guardian', 'knight'].map((key) => {
  const unit = UNITS.find((u) => u.key === key);
  return {
    key,
    name: unit.one,
    power: { id: `${key}.${SCHEMA.powerField}`, name: `${unit.one} power`, full: `${key} power` },
    production: { id: `${key}.${SCHEMA.unitField}`, name: `${unit.name}/t`, full: `${key} production` },
  };
});

const POWER_GOAL = UNIT_READINGS[0].power.id;
const UNIT_GOAL = UNIT_READINGS[0].production.id;

const OBJECTIVES = [...RESOURCE_OBJECTIVES,
{ ...UNIT_READINGS[0].power }, { ...UNIT_READINGS[0].production }];

/* Every goal is always listed, so this fixes only the order they break ties
   in: production before storage, and within each the reading order rather than
   the engine's enumerator order. The two that are neither come last. */
const GOAL_ORDER = ['wood.production', 'iron.production', 'soldiers.production', 'workers.production',
  'wood.storage', 'iron.storage', 'soldiers.storage', 'workers.storage', POWER_GOAL, UNIT_GOAL];

const SOLDIER_EFFICIENCIES = EFFICIENCIES.filter((e) => e.soldiers);

/* The three that scale worker production. Worker efficiency is a factor in
   all three; project efficiency is summed with it, map efficiency multiplies
   on top of it, so the worker entry is worker efficiency alone. */
const WORKER_EFFICIENCIES = EFFICIENCIES.filter((e) => e.workers);

// wood/t and iron/t after the market tax.
const MARKET_GOALS = [
  { base: 'wood.production', id: 'wood.production.market', name: 'Wood/t (mkt)', full: 'market wood production' },
  { base: 'iron.production', id: 'iron.production.market', name: 'Iron/t (mkt)', full: 'market iron production' },
];

const MARKET_BY_BASE = new Map(MARKET_GOALS.map((m) => [m.base, m]));

const SOLDIER_GOAL = 'soldiers.production';
const SOLDIER_MODES = [
  {
    key: 'base',
    id: SOLDIER_GOAL,
    name: 'Soldiers/t',
    full: 'soldier production',
    option: 'Base',
  },
  {
    key: 'attack',
    id: `${SOLDIER_GOAL}.attack`,
    name: 'Soldiers/t (atk)',
    full: 'effective attack soldier production',
    option: 'Atk',
  },
  {
    key: 'defense',
    id: `${SOLDIER_GOAL}.defense`,
    name: 'Soldiers/t (def)',
    full: 'effective defense soldier production',
    option: 'Def',
  },
];

const WORKER_GOAL = 'workers.production';
const WORKER_MODES = [
  {
    key: 'base',
    id: WORKER_GOAL,
    name: 'Workers/t',
    full: 'worker production',
    option: 'Base',
  },
  {
    key: 'worker',
    id: `${WORKER_GOAL}.worker`,
    name: 'Workers/t (age)',
    full: 'effective worker production',
    option: 'Age',
  },
  {
    key: 'map',
    id: `${WORKER_GOAL}.map`,
    name: 'Workers/t (map)',
    full: 'effective map worker production',
    option: 'Map',
  },
  {
    key: 'projects',
    id: `${WORKER_GOAL}.projects`,
    name: 'Workers/t (prj)',
    full: 'effective project worker production',
    option: 'Project',
  },
];

// Every goal the search accepts must be reachable from the menu, and vice versa.
(function everyGoalIsReachable() {
  const engine = new Set(SCHEMA.goals.map((g) => g.id));
  const page = new Set([...OBJECTIVES, ...MARKET_GOALS, ...SOLDIER_MODES, ...WORKER_MODES,
  ...UNIT_READINGS.flatMap((one) => [one.power, one.production])].map((g) => g.id));

  const unreachable = [...engine].filter((id) => !page.has(id));
  if (unreachable.length) throw new Error(`no menu entry for: ${unreachable.join(', ')}`);

  const invented = [...page].filter((id) => !engine.has(id));
  if (invented.length) throw new Error(`the search does not accept: ${invented.join(', ')}`);
}());

/* budget bounds each restart, not the search as a whole.

   Chosen from measurement: see tools/tune.py. These settings differ not in the
   mean result (all reach the same value on a small village) but in the spread
   on a large one. Eight restarts fell up to 18% below their own best run;
   sixteen never worse than 4%; twenty-four did not vary. Restarts are also
   what parallelises across workers, so they are the cheapest to raise. */
const EFFORTS = {
  fast: { restarts: 16, iterations: 60000, improvementPasses: 24, budget: 120000 },
  normal: { restarts: 24, iterations: 100000, improvementPasses: 40, budget: 200000 },
  thorough: { restarts: 64, iterations: 200000, improvementPasses: 60, budget: 400000 },
};

const EFFORT_FIELDS = ['restarts', 'iterations', 'improvementPasses', 'budget'];

/* A share is entered as a percentage, a factor as the factor itself, and a
   source added before or after the multiplication as the amount it adds. The
   last two share the shares' neutral of 0, so the engine's flags distinguish
   them. */
const GAME_MODIFIERS = SCHEMA.modifiers.map(({ id, neutral, minimum, addedBefore, addedAfter }) => {
  const amount = addedBefore || addedAfter; // an amount, not a share of one
  const percent = neutral === 0 && !amount;
  return {
    id, neutral, addedBefore, addedAfter,
    minimum: percent ? minimum * 100 : minimum,
    step: percent || amount ? 1 : 0.05,
    percent,
  };
});

const MODIFIER_BY_ID = new Map(GAME_MODIFIERS.map((m) => [m.id, m]));

// decimals serialize() writes a modifier to, which is what the engine gets
const MODIFIER_DECIMALS = 4;

// The three modifiers that belong to no resource or efficiency.
const STANDALONE_MODIFIERS = joined(GAME_MODIFIERS.filter((m) => !m.id.includes('.')), {
  quests: { name: 'Quests' },
  balance: { name: 'Balance' },
  market_tax_reduction: { name: 'Market tax reduction' },
}, 'standalone modifier');

// The multipliers that apply to every quantity at once.
const MODIFIER_SCALARS = STANDALONE_MODIFIERS.filter((m) => !m.percent);

// A market tax reduction is percentage points off the tax, not a share of it:
// -10 leaves 30% of the base 40%.
const MARKET_TAX = SCHEMA.baseMarketTax;
const MARKET_MODIFIERS = STANDALONE_MODIFIERS.filter((m) => m.percent);

// Crossed with every resource and rate-or-capacity to build the table.
const MODIFIER_SOURCES = joined(SCHEMA.modifierSources, {
  // named apart from a tile's terrain: these come from the world map
  terrain: { name: 'Terrain (world)' },
  terrain_flat: { name: 'Terrain (world)' },
  improvements: { name: 'Improvements' },
  shrine: { name: 'Shrine' },
  event_projects: { name: 'Event projects' },
  specialisation: { name: 'Specialisation' },
  projects: { name: 'Projects' },
  personal_project: { name: 'Personal project' },
  seasonal_events: { name: 'Seasonal events' },
  supply_upkeep: { name: 'Supply upkeep' },
  talents: { name: 'Talents' },
  redistribution: { name: 'Redistribution' },
}, 'modifier source');

/* Former ids of two modifier sources. A stored view or an exported layout
   written before the rename still uses the old id; this maps such a value onto
   its replacement. Read only: nothing is ever written under these names.

   Declared here rather than beside applyModifiers, its only caller, because
   restoreFromStorage runs before that point in the file and would hit the
   const's temporal dead zone. */
const SOURCE_WAS_CALLED = { event_projects: 'competitive_projects', seasonal_events: 'events' };

function modifierIn(fields, id) {
  if (Number.isFinite(fields[id])) return fields[id];

  const dot = id.lastIndexOf('.');
  const was = SOURCE_WAS_CALLED[id.slice(dot + 1)];
  return was === undefined ? undefined : fields[`${id.slice(0, dot)}.${was}`];
}

// The efficiencies and the powers take the same sources less the three
// resource-only ones.
const COMBAT_SOURCES = MODIFIER_SOURCES.filter((w) => !w.resourceOnly);

// One column of either modifier table: one quantity, with an input per source.
const RESOURCE_COLUMNS = RESOURCES.flatMap((r) => RATE_OR_CAPACITIES.map((m) => ({
  id: `${r.key}.${m.key}`, name: `${r.name}${m.suffix}`, cls: r.cls,
})));

const EFFICIENCY_COLUMNS = EFFICIENCIES.map((e) => ({
  id: `${SCHEMA.efficiencyField}.${e.key}`, name: e.name, cls: 'efficiency-value',
}));

// The three powers, then knight and guardian production.
const SUPPORT_COLUMNS = [
  ...POWERS.map((p) => ({ id: `${p.key}.${SCHEMA.powerField}`, name: p.name, cls: 'power-value' })),
  ...UNITS.map((u) => ({ id: `${u.key}.${SCHEMA.unitField}`, name: `${u.name}/t`, cls: 'power-value' })),
];

// A choice rather than a quantity: whichever production is selected is
// multiplied by POLITICS_BONUS.
const POLITICS_ID = SCHEMA.politicsField;
const NO_POLITICS = 'none';
const POLITICS_BONUS = SCHEMA.politicsBonus;
/* Politics uses lower-case ids of its own: it is this page's model of the
   bonus, not something the game api describes. */
const POLITICS = joined(SCHEMA.politics, {
  none: { name: 'None', favours: null },
  resource: { name: 'Resource', favours: 'the wood and iron produced' },
  worker: { name: 'Worker', favours: 'the workers produced' },
  soldier: { name: 'Soldier', favours: 'the soldiers produced' },
}, 'politics');

const POLITICS_KEYS = new Set(POLITICS.map((p) => p.key));

const politicsNote = ({ favours }) => (favours === null ? 'No bonus.' : `×${POLITICS_BONUS} ${favours}.`);

const [EAST, SOUTH, WEST, NORTH] = SCHEMA.orientations;

const CENTRE_TIERS = [
  { from: 20, img: `${ART}/town_center_20.png` },
  { from: 15, img: `${ART}/town_center_15.png` },
  { from: 10, img: `${ART}/town_center_10.png` },
  { from: 5, img: `${ART}/town_center_5.png` },
  { from: 0, img: `${ART}/town_center_1.png` },
];

function buildingImage(key, level) {
  if (key === CENTRE) return CENTRE_TIERS.find((tier) => level >= tier.from).img;
  return BUILDING_BY_KEY.get(key).img;
}

const PLACEABLE = BUILDINGS.filter((b) => b.key !== EMPTY && b.key !== CENTRE);

function placeableInTier(tier) {
  return PLACEABLE.filter((b) => b.tier === tier);
}

const TERRAIN_BY_KEY = new Map(TERRAINS.map((t) => [t.key, t]));
const BUILDING_BY_KEY = new Map(BUILDINGS.map((b) => [b.key, b]));

/* The games the engine carries, newest first, and the one being planned
   against. They differ in terrain and in rules. */
const GAMES = SCHEMA.games;
const GAME_BY_ID = new Map(GAMES.map((g) => [g.id, g]));

// Rebuilt by readEffects whenever the selected game changes.
let effectsByBuilding = new Map();
let shapeByBuilding = new Map();

// A game's flat terrain list reshaped into rows, for indexing by x and y.
function terrainRows(game) {
  const rows = [];
  for (let y = 0; y < game.height; y += 1) {
    rows.push(game.terrain.slice(y * game.width, (y + 1) * game.width));
  }
  return rows;
}

function index(x, y) {
  return y * WIDTH + x;
}

function span(className, text = '') {
  const el = document.createElement('span');
  el.className = className;
  if (text) el.textContent = text;
  return el;
}

// Every <select> on the page is built from value, label and optional tooltip.
function addOption(select, value, text, title = '') {
  const option = document.createElement('option');
  option.value = value;
  option.textContent = text;
  if (title) option.title = title;
  select.append(option);
  return option;
}

// What an exception has to say, whether or not it is an Error.
function reason(err) {
  return String(err?.message ?? err);
}

function plural(n, word) {
  return `${n} ${word}${n === 1 ? '' : 's'}`;
}

// A cell's index, or null if the coordinates fall outside the grid.
function cellAt(x, y) {
  return x >= 0 && x < WIDTH && y >= 0 && y < HEIGHT ? index(x, y) : null;
}

/* The offsets of a shape's cells from its anchor, which is always [0, 0] and
   comes first; grid edges are not considered. Mirrors footprintOf in
   village.cpp: Line is the anchor plus the tile east or south of it; Square is
   a fixed 2x2 block right of and below the anchor; LShape is the anchor (the
   corner tile) plus the pair of arms the orientation selects. */
function footprintOffsets(key, orientation) {
  const shape = shapeOf(key);
  if (shape === 'single') return [[0, 0]];
  if (shape === 'line') return [[0, 0], orientation === SOUTH ? [0, 1] : [1, 0]];
  if (shape === 'square') return [[0, 0], [1, 0], [0, 1], [1, 1]];

  const arms = {
    [EAST]: [[1, 0], [0, 1]],
    [SOUTH]: [[0, 1], [-1, 0]],
    [WEST]: [[-1, 0], [0, -1]],
    [NORTH]: [[0, -1], [1, 0]],
  }[orientation] ?? [[1, 0], [0, 1]];
  return [[0, 0], ...arms];
}

// The cells a shape covers when anchored at i, or null if any falls outside
// the grid.
function footprintCells(i, key, orientation) {
  const x = i % WIDTH;
  const y = Math.floor(i / WIDTH);
  const cells = footprintOffsets(key, orientation).map(([dx, dy]) => cellAt(x + dx, y + dy));
  return cells.some((c) => c === null) ? null : cells;
}

/* The tile the level badge is drawn on: the southernmost cell, and the
   easternmost of those. Indices run row by row, so that is their maximum. */
function levelCell(tiles, anchor) {
  const tile = tiles[anchor];
  const cells = footprintCells(anchor, tile.building, tile.orientation);
  return cells === null ? anchor : Math.max(...cells);
}

// tile index -> anchor index of the building covering it, or null.
function occupancyMap(tiles) {
  const map = new Array(TILE_COUNT).fill(null);
  for (let i = 0; i < TILE_COUNT; i += 1) {
    const tile = tiles[i];
    if (tile.building === EMPTY) continue;
    const cells = footprintCells(i, tile.building, tile.orientation) ?? [i];
    for (const cell of cells) map[cell] = i;
  }
  return map;
}

// The next orientation while placing or dragging: a Line alternates East and
// South; an LShape advances one quarter-turn clockwise.
function rotate(key, orientation) {
  if (shapeOf(key) === 'line') return orientation === SOUTH ? EAST : SOUTH;
  return { [EAST]: SOUTH, [SOUTH]: WEST, [WEST]: NORTH, [NORTH]: EAST }[orientation] ?? EAST;
}

// Whether the building covers more than one cell, which decides collision,
// stranding and the spanning icon, independently of whether it can be turned.
function isMultiTile(key) {
  return shapeOf(key) !== 'single';
}

// Whether the rotate control does anything: a Square is identical in every
// orientation.
function isRotatable(key) {
  const shape = shapeOf(key);
  return shape === 'line' || shape === 'l';
}

function fmt(value, digits = 2) {
  if (!Number.isFinite(value)) return '0';
  return String(Number(value.toFixed(digits)));
}

function pct(value) {
  return `${value >= 0 ? '+' : ''}${fmt(value * 100, 1)}%`;
}

function fmtStore(value) {
  if (!Number.isFinite(value)) return '0';
  return Math.round(value).toLocaleString('en-US');
}

function fmtStoreShort(value) {
  if (!Number.isFinite(value)) return '0';
  if (value < 1000) return String(Math.round(value));
  return `${fmt(value / 1000, value < 10000 ? 1 : 0)}k`;
}

function readEffects(id) {
  const game = GAME_BY_ID.get(id) ?? GAMES[0];
  effectsByBuilding = new Map();
  for (const effect of game.effects) {
    if (!effectsByBuilding.has(effect.building)) effectsByBuilding.set(effect.building, []);
    effectsByBuilding.get(effect.building).push(effect);
  }

  // Shape is per game too: a building can occupy one tile in one round and
  // three in the next.
  shapeByBuilding = new Map(game.shapes.map((s) => [s.building, s.shape]));
}

function shapeOf(key) {
  return shapeByBuilding.get(key) ?? 'single';
}

function neighbours(i) {
  const x = i % WIDTH;
  const y = Math.floor(i / WIDTH);
  const out = [];
  if (x > 0) out.push(i - 1);
  if (x + 1 < WIDTH) out.push(i + 1);
  if (y > 0) out.push(i - WIDTH);
  if (y + 1 < HEIGHT) out.push(i + WIDTH);
  return out;
}

function attachEngine(module) {
  const call = (name, ...args) => {
    const pointers = args.map((text) => module.stringToNewUTF8(text));
    const out = module.ccall(name, 'number', args.map(() => 'number'), pointers);
    for (const pointer of pointers) module._free(pointer);

    const answer = module.UTF8ToString(out);
    module._apiFree(out);

    // WebAssembly cannot propagate an exception across the boundary, so a
    // rejection is returned as text prefixed with '!'. See src/wasm.cpp.
    if (answer.startsWith('!')) throw new Error(answer.slice(1));
    return answer;
  };

  return {
    parse: (body) => call('apiParse', body),
    production: (body) => call('apiProduction', body),
    rearrange: (body, goal, effort) => call('apiRearrange', body, goal, effort),
    simulate: (script) => call('apiSimulate', script),
  };
}

/* ---------------------------- export and import ---------------------------

   A layout or a run travels as base64 of a small JSON envelope, so that what
   is pasted about is one unbroken token rather than something a chat client
   will reflow. */

function toBase64(text) {
  const bytes = new TextEncoder().encode(text);
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function fromBase64(text) {
  const binary = atob(text.replace(/\s+/g, ''));
  return new TextDecoder().decode(Uint8Array.from(binary, (c) => c.charCodeAt(0)));
}

/* ----------------------------- game modifiers -----------------------------

   The modifiers panel: every field the engine describes, in the same groups on
   both pages. Built here rather than on either page so the two cannot drift
   apart, which they did once already.

   The page hands in the object its own state keeps the values in; this writes
   into it and calls `changed` afterwards. */

const modifierInputs = new Map();
let politicsSelect = null;

function modifierInput(id, values, changed) {
  const field = MODIFIER_BY_ID.get(id);

  const input = document.createElement('input');
  input.type = 'number';
  input.className = 'modifier-input';
  input.min = String(field.minimum);
  input.step = String(field.step);
  input.value = String(field.neutral);
  input.dataset.mod = id;

  input.addEventListener('input', () => {
    const typed = Number(input.value);
    values[id] = Number.isFinite(typed) ? Math.max(field.minimum, typed) : field.neutral;
    renderModifierPanel(values);
    changed();
  });

  modifierInputs.set(id, input);
  return input;
}

function politicsPicker(values, changed) {
  const select = document.createElement('select');
  select.className = 'modifier-select';
  select.dataset.mod = POLITICS_ID;

  for (const choice of POLITICS) addOption(select, choice.key, choice.name, politicsNote(choice));
  select.value = NO_POLITICS;

  select.addEventListener('change', () => {
    values[POLITICS_ID] = POLITICS_KEYS.has(select.value) ? select.value : NO_POLITICS;
    renderModifierPanel(values);
    changed();
  });

  politicsSelect = select;
  return select;
}

// A column of standalone fields, each labelled and marked with its unit.
function buildFieldColumn(containerId, fields, unit, values, changed) {
  const column = document.getElementById(containerId);

  for (const field of fields) {
    const label = document.createElement('label');
    label.className = 'modifier-field';
    label.append(span('', field.name), span('modifier-unit', unit), modifierInput(field.key, values, changed));
    column.append(label);
  }
}

function buildModifierTable(bodyId, columns, sources, values, changed) {
  const body = document.getElementById(bodyId);

  const head = document.createElement('tr');
  head.append(document.createElement('th'));
  for (const column of columns) {
    const th = document.createElement('th');
    th.textContent = column.name;
    th.className = column.cls;
    head.append(th);
  }
  body.append(head);

  for (const source of sources) {
    const tr = document.createElement('tr');
    const th = document.createElement('th');
    th.className = 'modifier-row-name';
    th.textContent = `${source.name} ${source.addedBefore ? '+' : (source.share ? '%' : '×')}`;
    tr.append(th);

    for (const column of columns) {
      const td = document.createElement('td');
      td.append(modifierInput(`${column.id}.${source.key}`, values, changed));
      tr.append(td);
    }
    body.append(tr);
  }
}

function buildModifierPanel(values, changed) {
  const scalars = document.getElementById('modifier-scalars');
  buildFieldColumn('modifier-scalars', MODIFIER_SCALARS, '×', values, changed);
  buildFieldColumn('modifier-market', MARKET_MODIFIERS, '%', values, changed);

  // Politics sits with the scalars it multiplies alongside; it is chosen from
  // a list rather than entered.
  const politics = document.createElement('label');
  politics.className = 'modifier-field modifier-choice';
  politics.append(span('', 'Politics'), politicsPicker(values, changed));
  scalars.append(politics);

  // Resource columns follow the goal menu's order: rate first, then capacity,
  // both in their resource's colour.
  buildModifierTable('modifier-columns', RESOURCE_COLUMNS, MODIFIER_SOURCES, values, changed);
  buildModifierTable('modifier-efficiency', EFFICIENCY_COLUMNS, COMBAT_SOURCES, values, changed);
  buildModifierTable('modifier-support', SUPPORT_COLUMNS, COMBAT_SOURCES, values, changed);
}

function renderModifierPanel(values) {
  const politics = values[POLITICS_ID];
  const set = GAME_MODIFIERS.filter((m) => values[m.id] !== m.neutral).length
    + (politics === NO_POLITICS ? 0 : 1);
  const summary = document.getElementById('modifiers-summary');
  summary.textContent = set === 0 ? 'all neutral' : `${plural(set, 'field')} set`;
  summary.classList.toggle('modifiers-set', set > 0);

  for (const [id, input] of modifierInputs) {
    const value = values[id];
    if (document.activeElement !== input && Number(input.value) !== value) {
      input.value = String(value);
    }
    input.classList.toggle('modifier-on', value !== MODIFIER_BY_ID.get(id).neutral);
  }

  politicsSelect.value = politics;
  politicsSelect.title = politicsNote(POLITICS.find((p) => p.key === politics));
  politicsSelect.classList.toggle('modifier-on', politics !== NO_POLITICS);
}

/* ---------------------------- saved villages ------------------------------

   The layouts the planner keeps in this browser. The planner writes them; the
   simulator reads them to start a run from one, so the shape they are checked
   against is stated once, here. A save carries the board and nothing else: no
   modifiers, and no round, since the terrain travels in the layout itself. */

const PLANNER_SAVES = 'factions-solver/v1/saves';

function readPlannerSaves() {
  try {
    const raw = JSON.parse(localStorage.getItem(PLANNER_SAVES));
    if (!Array.isArray(raw)) return [];
    return raw.filter((one) => one !== null && typeof one === 'object'
      && typeof one.name === 'string' && one.name !== ''
      && typeof one.layout === 'string');
  } catch {
    return [];
  }
}

/* The buildings adjacent to a footprint, one entry per building however many
   of its tiles touch, and never the building itself. Read through the
   occupancy map, since only a multi-tile building's anchor holds its key. */
function buildingsBeside(board, anchor, cells) {
  const occupancy = occupancyMap(board.tiles);
  const anchors = new Set();

  for (const cell of cells) {
    for (const j of neighbours(cell)) {
      if (occupancy[j] !== null && occupancy[j] !== anchor) anchors.add(occupancy[j]);
    }
  }
  return [...anchors].map((one) => board.tiles[one].building);
}

/* --------------------------- describing a tile ---------------------------

   What a building does and what it costs, as the panel beside the board shows
   it. Both pages show the same thing, so it is written once here.

   `board` is what the page has on the board and what the engine last said
   about it: { tiles, result, terrainBonusFactor }. Nothing else is read from
   the page. */

// The resources a level is paid in, in the order the game lists them.
// Soldiers are not spent, so they are excluded.
const COSTED = ['wood', 'iron', 'workers'];
const NO_COST = { wood: 0, iron: 0, workers: 0 };

function anyCost(cost) {
  return COSTED.some((r) => cost[r] > 0);
}

// The cost entry for one building, or for the village. The engine computes
// both and returns them with the rest of the reply.
function costAt(board, anchor) {
  const cost = board.result?.cost;
  if (!cost || anchor === null) return null;
  if (board.tiles[anchor].building === CENTRE) return cost.village;
  return cost.buildings.find((one) => one.tile === anchor) ?? null;
}

/* Every effect a building has in the selected game, whether or not it applies
   on this tile. These are the effects the engine computes from, so the panel
   and the arithmetic cannot diverge.

   Ordered as the game presents them: what the building does unconditionally,
   then one block per terrain it responds to, then what its neighbours
   contribute; blocks that do not currently apply are shown greyed. */




const QUANTITY_NAMES = {
  wood: 'Wood', iron: 'Iron', workers: 'Workers', soldiers: 'Soldiers',
  knight: 'Knight', guardian: 'Guardian', market_order: 'Market orders',
  build_order: 'Build orders', attack: 'Attack', defense: 'Defense',
  market_tax: 'Market tax',
  knightPower: 'Knight power', guardianPower: 'Guardian power',
  map_efficiency: 'Map efficiency', worker_project_efficiency: 'Project efficiency',
  recycling: 'Recycling', specialization: 'Specialisation',
};

// Quantities the engine carries through to the totals. The rest are displayed
// and labelled as uncounted rather than silently dropped.
const COUNTED = new Set(['wood', 'iron', 'workers', 'soldiers', 'knight', 'guardian',
  'attack', 'defense', 'map_efficiency', 'worker_project_efficiency',
  'knightPower', 'guardianPower', 'market_tax', 'efficiency']);

// Quantities the Makes and Holds blocks already total, so Total skips them.
const COUNTED_IN_OUTPUT = new Set(['wood', 'iron', 'workers', 'soldiers', 'efficiency']);

const QUANTITY_CLASS = {
  wood: 'wood-value', iron: 'iron-value', workers: 'workers-value', soldiers: 'soldiers-value',
};

/* An `efficiency` effect names no resource: it multiplies whatever its targets
   produce or store. Where every target produces exactly one quantity on that
   side, the label names it, so a sawmill reads "Wood production" rather than an
   unqualified boost. An arena targets barracks producing soldiers and mercenary
   offices producing two quantities, so it stays a boost. */
const BOOST_NAMES = { both: 'Output boost', production: 'Production boost', storage: 'Storage boost' };

function onlyQuantityBoosted(effect) {
  if (effect.on.length === 0) return null;

  const found = new Set();
  for (const target of effect.on) {
    for (const its of effectsByBuilding.get(target) ?? []) {
      if (its.where !== 'base' && its.where !== 'terrain') continue;
      if (its.quantity === 'efficiency' || its.rateOrCapacity !== effect.rateOrCapacity) continue;
      found.add(its.quantity);
    }
  }
  return found.size === 1 ? [...found][0] : null;
}

// World-map ratings, which are neither production nor storage.
const WORLD_RATINGS = new Set(['attack', 'defense', 'knightPower', 'guardianPower',
  'map_efficiency', 'worker_project_efficiency']);

// The two of those that are a power rather than an efficiency: their names
// already say what they are, so nothing is appended to them.
const WORLD_POWERS = new Set(['knightPower', 'guardianPower']);

function effectLabel(effect) {
  if (WORLD_RATINGS.has(effect.quantity)) {
    const rating = QUANTITY_NAMES[effect.quantity] ?? effect.quantity;
    return WORLD_POWERS.has(effect.quantity) ? rating : `${rating} efficiency`;
  }
  if (effect.quantity === 'efficiency') {
    const only = onlyQuantityBoosted(effect);
    if (only !== null) return `${QUANTITY_NAMES[only] ?? only} ${effect.rateOrCapacity}`;
    return BOOST_NAMES[effect.rateOrCapacity] ?? 'Output boost';
  }

  const named = QUANTITY_NAMES[effect.quantity] ?? effect.quantity;
  if (effect.rateOrCapacity === 'both' || effect.quantity === 'market_tax') return named;
  return `${named} ${effect.rateOrCapacity}`;
}

// The same wording for an aura read off the reply, which names its source but
// not what that source targets.
function auraLabel(board, from, rateOrCapacity) {
  const provided = (effectsByBuilding.get(from) ?? []).find(
    (e) => e.where === 'provides' && e.rateOrCapacity === rateOrCapacity,
  );
  return provided === undefined
    ? BOOST_NAMES[rateOrCapacity] ?? 'Output boost'
    : effectLabel(provided);
}

/* Which seal multiplies a rate and which a capacity. A quantity that names
   neither is treated as a rate, as the engine's resolveRateOrCapacity does. */
const SEAL_FOR_RATE_OR_CAPACITY = { production: 'ECONOMIC_BOOST', storage: 'STORAGE_EXPANDER', both: 'ECONOMIC_BOOST' };

/* Whether the seal on this tile multiplies what this row contributes.

   A mill multiplies what a tile produces and a barrel what it stores, so
   neither applies to an aura, a rating or the tax: none of those is a resource
   of this tile. Where the building has a base of its own, the seal multiplies
   that base, which the flat row already carries, so the shares and factors
   over it are left alone rather than counted twice. Where it has none, its
   village-wide contribution passes through the seal, except a share that does
   not scale with level: that one is village-wide outright (see effects.cpp). */
function sealScales(effect, seal, effects) {
  if (seal !== SEAL_FOR_RATE_OR_CAPACITY[effect.rateOrCapacity]) return false;
  if (!GLOBAL_RESOURCES.includes(effect.quantity) || effect.where === 'provides') return false;
  if (hasBaseOfItsOwn(effect, effects)) return effect.amount === 'flat';
  return effect.amount !== 'share' || effect.perLevel;
}

/* Whether the building has a base of its own for the shares and factors to
   multiply, from any source: a house stores soldiers only when adjacent to a
   guard tower, and that is still its own quantity rather than the village's. */
function hasBaseOfItsOwn(effect, effects) {
  return effects.some((its) => its.amount === 'flat'
    && its.quantity === effect.quantity && its.rateOrCapacity === effect.rateOrCapacity);
}

/* A master builder's seal multiplies the level that per-level effects scale
   by; a mill or a barrel multiplies the quantity itself. A factor accumulates
   the way the game writes it: 1.05 per level at level 39 is 1 + 0.05 * 39 =
   x2.95, not 1.05^39. */
function effectTimes(effect, level, seal, over = 1, effects = []) {
  return over
    * (effect.perLevel ? level * (seal === 'LEVEL_BOOST' ? MASTER_LEVEL_BONUS : 1) : 1)
    * (sealScales(effect, seal, effects) ? SEAL_BONUS : 1);
}

function effectAmount(effect, level, seal, over = 1, effects = []) {
  const times = effectTimes(effect, level, seal, over, effects);

  if (effect.amount === 'multiply') return `×${fmt(1 + (effect.value - 1) * times, 2)}`;
  if (effect.amount === 'share') return `+${fmt(effect.value * 100 * times, 1)}%`;

  const value = effect.value * times;
  if (effect.quantity === 'market_tax') return `${fmt(value * 100, 1)}%`;
  const shown = Math.abs(value) >= 1000 ? fmtStore(value) : fmt(value, 2);
  return value < 0 ? shown : `+${shown}`;
}

/* A share with no base of the building's own applies to the village instead.
   Shares that do not scale with level are village-wide outright: a furnace on
   plains contributes its ten percent regardless of its neighbours, its seal
   and its level, so they are marked and excluded from the building's own
   total. Shares that scale with level are not marked and do count towards it. */
function ownFigureFor(effect, effects) {
  return effects.some((its) => its.amount === 'flat'
    && its.quantity === effect.quantity && its.rateOrCapacity === effect.rateOrCapacity
    && (its.where === 'base' || its.where === 'terrain'));
}

function goesToWholeVillage(effect, effects) {
  return effect.amount !== 'flat' && !effect.perLevel
    && (effect.where === 'base' || effect.where === 'terrain')
    && !ownFigureFor(effect, effects);
}

function effectRow(effect, level, seal, from = '', times = 1, dim = false, effects = [], explains = '') {
  const notes = (COUNTED.has(effect.quantity) ? '' : '<span class="fx-note">not counted</span>')
    + (effect.perLevel ? '<span class="fx-note" title="Scales with the building\'s level">&uarr;lvl</span>' : '')
    + (goesToWholeVillage(effect, effects)
      ? '<span class="fx-note fx-global" title="Worth this to the whole village, not to this tile">global</span>'
      : '');

  // A factor is rendered green, a share or a flat amount white.
  const kind = effect.amount === 'multiply' ? 'fx-times' : 'fx-plus';

  return `<li${dim ? ' class="fx-dim"' : ''}><span class="fx-what">${effectLabel(effect)}</span>`
    + `<span class="fx-value ${kind}${explains === '' ? '' : ' fx-explained'}" ${explains}>`
    + `${effectAmount(effect, level, seal, times, effects)}</span>${notes}`
    + (from === '' ? '' : `<span class="fx-from">${from}</span>`)
    + '</li>';
}

function effectBlock(title, kind, live, rows) {
  if (rows.length === 0) return '';
  return `<h4 class="fx-head fx-${kind}${live ? '' : ' fx-dim'}">${title}</h4>`
    + `<ul class="fx-list fx-${kind}${live ? '' : ' fx-dim'}">${rows.join('')}</ul>`;
}

/* What the engine scales a terrain effect by over the tiles a building
   covers: one per matching tile, terrainBonusFactor where terraformed. */
function terrainScale(board, cells, ground) {
  const factor = board.terrainBonusFactor ?? 1;
  let scale = 0;

  for (const cell of cells) {
    if (board.tiles[cell].terrain !== ground) continue;
    scale += board.tiles[cell].terraformed === true ? factor : 1;
  }
  return scale;
}

// The auras reaching a tile, as rows for the adjacency block: the factor and
// the neighbour providing it.
function aurasOn(board, anchor, cells) {
  if (!board.result) return [];

  const { modifiers } = board.result;
  const twice = new Set(modifiers
    .map((m) => m.from)
    .filter((from, at, all) => all.indexOf(from) !== at));

  const beside = buildingsBeside(board, anchor, cells);

  return modifiers
    .filter((m) => cells.some((cell) => m.values[cell] !== 0))
    .map((m) => {
      const named = BUILDING_BY_KEY.get(m.from)?.name ?? m.from;
      const count = beside.filter((b) => b === m.from).length;
      const reaching = cells.reduce((sum, cell) => sum + m.values[cell], 0);
      const from = twice.has(m.from) ? `${named} (${m.rateOrCapacity})` : named;

      return `<li><span class="fx-what">${auraLabel(board, m.from, m.rateOrCapacity)}</span>`
        + `<span class="fx-value">×${fmt(1 + reaching, 2)}</span>`
        + `<span class="fx-from">${count > 1 ? `${from} ×${count}` : from}</span></li>`;
    });
}

/* The auras reaching a tile that multiply one quantity, as
   Rules::aurasThatMultiply picks them: over efficiency multiplies every
   quantity, one named for a quantity that one alone, one over both a rate and
   a capacity alike. A building covering several tiles is reached once. */
function aurasMultiplying(board, cells, quantity, rateOrCapacity) {
  if (!board.result) return [];

  return board.result.modifiers
    .filter((aura) => aura.quantity === SCHEMA.efficiencyField || aura.quantity === quantity)
    .filter((aura) => aura.rateOrCapacity === 'both' || aura.rateOrCapacity === rateOrCapacity)
    .map((aura) => ({ from: aura.from, value: 1 + cells.reduce((sum, cell) => sum + aura.values[cell], 0) }))
    .filter((aura) => aura.value !== 1);
}

/* What one building accumulates, from the same rules the rows above are drawn
   from. Shares and factors are summed and multiplied separately, since shares
   add into the sum and factors multiply it. Flat shares are excluded, being
   village-wide rather than this building's.

   Where the building has no base of its own, what it contributes goes to the
   village and the auras reaching this tile multiply it, exactly as they
   multiply the output of a building that has one. Where it has a base, that
   base is what they multiply, and the tile's own figure already carries them,
   so counting them here as well would count them twice.

   Attack, defense and the tax also pass through here: the engine counts them
   into no resource, so it reports no per-tile value for them. */
function effectTotals(board, anchor, level) {
  const tile = board.tiles[anchor];
  const effects = effectsByBuilding.get(tile.building) ?? [];
  const cells = footprintCells(anchor, tile.building, tile.orientation) ?? [anchor];
  const beside = buildingsBeside(board, anchor, cells);

  const totals = new Map();
  for (const effect of effects) {
    const times = effectReach(board, cells, beside, effect);
    if (times === 0 || goesToWholeVillage(effect, effects)) continue;

    const key = `${effect.quantity}|${effect.rateOrCapacity}`;
    const running = totals.get(key) ?? {
      quantity: effect.quantity,
      rateOrCapacity: effect.rateOrCapacity,
      // a per-level share is multiplied by the auras; a flat one is village-wide outright
      perLevelShare: 0,
      flatShare: 0,
      factor: 1,
      counted: 0,
      from: [],
      toVillage: !hasBaseOfItsOwn(effect, effects),
    };

    const scaled = effectTimes(effect, level, tile.seal, times, effects);
    if (effect.amount === 'share') {
      if (effect.perLevel) running.perLevelShare += effect.value * scaled;
      else running.flatShare += effect.value * scaled;
    } else if (effect.amount === 'multiply') {
      running.factor *= 1 + (effect.value - 1) * scaled;
    }
    running.counted += 1;
    running.from.push({ effect, times, ground: effectGround(board, cells, effect) });

    totals.set(key, running);
  }

  const finished = [...totals.values()].map((one) => {
    const auras = one.toVillage ? aurasMultiplying(board, cells, one.quantity, one.rateOrCapacity) : [];
    const reaching = auras.reduce((product, aura) => product * aura.value, 1);

    return {
      ...one,
      auras,
      // What the building came to before any aura reached it, kept so the
      // panel can show the two apart.
      ownFactor: one.factor,
      share: one.perLevelShare * reaching + one.flatShare,
      // A factor is stored as the factor and contributed as what it adds, so
      // the auras multiply the amount above one rather than the factor.
      factor: 1 + (one.factor - 1) * reaching,
    };
  });

  /* A building with a figure of its own has it reported per tile, with these
     shares and factors already counted into it, so repeating them here would
     state them twice. What goes to the village has no such figure, and nor do
     the quantities the engine counts into no resource: a rating or the tax is
     reported for the village alone, so its row is the only place it shows.

     Rows carrying a share come first, as the game orders them. */
  return finished
    .filter((one) => one.share !== 0 || one.factor !== 1)
    .filter((one) => one.toVillage || !GLOBAL_RESOURCES.includes(one.quantity))
    .sort((a, b) => (b.share !== 0) - (a.share !== 0));
}

/* Shares and factors get a column each, so the values align down the block
   instead of following the label. A block with no factors needs one column.

   Each figure carries what it would take to explain it, so that clicking it
   opens the same panel the stats panel uses. */
function totalRow(one, withFactors, anchor) {
  const share = one.share === 0 ? ''
    : `${one.share > 0 ? '+' : ''}${fmt(one.share * 100, 1)}%`;
  const explains = `data-tile-total="${anchor}|${one.quantity}|${one.rateOrCapacity}"`;

  return `<li><span class="fx-what">${effectLabel(one)}</span>`
    + `<span class="fx-value fx-plus${share === '' ? '' : ' fx-explained'}" ${share === '' ? '' : explains}>${share}</span>`
    + (withFactors
      ? `<span class="fx-value fx-times${one.factor === 1 ? '' : ' fx-explained'}" ${one.factor === 1 ? '' : explains}>${one.factor === 1 ? '' : `×${fmt(one.factor, 2)}`}</span>`
      : '')
    + '</li>';
}

function buildingEffects(board, anchor, level, auraRows = []) {
  const tile = board.tiles[anchor];
  const effects = effectsByBuilding.get(tile.building) ?? [];
  if (effects.length === 0) return '';

  const cells = footprintCells(anchor, tile.building, tile.orientation) ?? [anchor];
  const standing = new Set(cells.map((cell) => board.tiles[cell].terrain));
  const beside = buildingsBeside(board, anchor, cells);

  let html = effectBlock('Effects', 'base', true,
    effects.filter((e) => e.where === 'base')
      .map((e) => effectRow(e, level, tile.seal, '', 1, false, effects)));

  /* One block per terrain this building responds to, applying or not. A
     terrain it does not stand on is shown at what one matching tile would be
     worth: the block is already greyed, so the figure says what moving the
     building would gain. The adjacency rows below read the same way. */
  const grounds = [...new Set(effects.filter((e) => e.where === 'terrain').flatMap((e) => e.on))];
  for (const ground of grounds) {
    const matching = cells.filter((cell) => board.tiles[cell].terrain === ground).length;
    const scale = terrainScale(board, cells, ground);
    const rows = effects
      .filter((e) => e.where === 'terrain' && e.on.includes(ground))
      .map((e) => effectRow(e, level, tile.seal, '', Math.max(scale, 1), false, effects));
    const named = TERRAIN_BY_KEY.get(ground)?.name ?? ground;
    const live = standing.has(ground);
    /* Covered tiles of this terrain, which says something only over several
       tiles with some matching: on one tile it repeats the name, and where
       none match the cross has said so. */
    const counted = cells.length > 1 && matching > 0 ? ` ${matching}/${cells.length}` : '';
    // the rows above already carry it; this names it
    const fertile = scale > matching
      ? `<li class="fx-fertile">+ ${FERTILE_GROUNDS} +${fmt((board.terrainBonusFactor - 1) * 100, 2)}%</li>`
      : '';
    html += effectBlock(`${live ? named : `✗ ${named}`}${counted}`, 'terrain', live,
      rows.length === 0 ? rows : [...rows, fertile]);
  }

  /* One row per building an adjacency effect names, worth its value times the
     number of them adjacent. A target with none adjacent is still shown,
     greyed and at its single-neighbour value, so the requirement is visible. */
  const fromNeighbours = effects.filter((e) => e.where === 'adjacent');
  const wanted = [...new Set(fromNeighbours.flatMap((e) => e.on))];

  const adjacent = [];
  for (const want of wanted) {
    const count = beside.filter((b) => b === want).length;
    const named = BUILDING_BY_KEY.get(want)?.name ?? want;

    for (const effect of fromNeighbours.filter((e) => e.on.includes(want))) {
      adjacent.push({
        row: effectRow(effect, level, tile.seal, count > 1 ? `${named} ×${count}` : named,
          Math.max(count, 1), count === 0, effects),
        live: count > 0,
      });
    }
  }

  const adjacencyRows = adjacent.map((a) => a.row).concat(auraRows);
  if (adjacencyRows.length > 0) {
    html += effectBlock('Adjacency bonus', 'adj',
      adjacent.some((a) => a.live) || auraRows.length > 0, adjacencyRows);
  }

  /* What this building gives its neighbours, at what the engine wrote to
     their tiles: the auras reaching this tile do not scale it. */
  const gives = effects.filter((e) => e.where === 'provides').map((e, n) => {
    const reaches = e.on.length === 0
      ? 'every neighbour'
      : `adjacent ${e.on.map((want) => (e.byCategory
        ? `${want.toLowerCase()} buildings`
        : (BUILDING_BY_KEY.get(want)?.name ?? want).toLowerCase())).join(', ')}`;

    return effectRow(e, level, tile.seal, '', 1, false, effects,
      `data-tile-aura="${anchor}|${n}"`)
      .replace('</li>', `<span class="fx-reaches">to ${reaches}</span></li>`);
  });
  html += effectBlock('Aura', 'gives', true, gives);


  return html;
}

/* What this building has cost so far and what its next level costs, side by
   side. Both come from the engine, priced against the selected round. */
function costBlock(board, anchor) {
  const cost = costAt(board, anchor);
  if (cost === null) return '';

  const village = board.tiles[anchor].building === CENTRE;
  const rows = COSTED
    .filter((resource) => cost.next[resource] > 0 || cost.spent[resource] > 0)
    .map((resource) => `<li><span class="fx-what">${resource}</span>`
      + `<span class="fx-value ${resource}-value">`
      + `${cost.next[resource] > 0 ? fmtStore(cost.next[resource]) : '—'}</span>`
      + `<span class="fx-value">`
      + `${cost.spent[resource] > 0 ? fmtStore(cost.spent[resource]) : '—'}</span></li>`);
  if (rows.length === 0) return '';

  const next = anyCost(cost.next) ? `to lvl ${cost.level + 1}` : 'at its highest';
  const columns = '<li class="fx-cols"><span class="fx-what"></span>'
    + `<span class="fx-value" title="What the next level costs">${next}</span>`
    + `<span class="fx-value" title="Everything paid to reach level ${cost.level}">spent</span></li>`;

  return effectBlock(village ? 'Village levels' : 'Cost', 'cost', true, [columns, ...rows]);
}

/* The whole detail pane for one tile: what the building standing there does,
   what the tile comes to, and what it cost. `anchor` is the tile the building
   is stored on, which is `i` itself for bare ground and for a single tile. */
function tileDetail(board, i, anchor) {
  lastBoard = board;
  const owner = anchor === null ? null : board.tiles[anchor];

  let html = '';
  if (owner !== null) {
    html += buildingEffects(board, anchor, owner.level,
      aurasOn(board, anchor, footprintCells(anchor, owner.building, owner.orientation) ?? [anchor]));
  }

  /* The tile's totals, counting everything above: the resources the engine
     computed, then the ratings it carries but does not count. */
  const totals = [];
  if (board.result) {
    const { tiles } = board.result;
    const src = anchor === null ? i : anchor;

    // Each figure carries its breakdown id and tile, so a click narrows to this tile.
    const line = (name, value, cls, id) => `<li><span class="fx-what">${name}</span>`
      + `<span class="fx-value ${cls} fx-explained" data-breakdown="${id}" data-tile="${src}">${value}</span></li>`;

    for (const r of RESOURCES) {
      if (tiles.production[r.key][src] > 0) {
        totals.push(line(`${r.name} production`, `+${fmt(tiles.production[r.key][src], 3)}`, r.cls, `${r.key}.production`));
      }
    }
    for (const r of RESOURCES) {
      if (tiles.storage[r.key][src] > 0) {
        totals.push(line(`${r.name} storage`, `+${fmtStore(tiles.storage[r.key][src])}`, r.cls, `${r.key}.storage`));
      }
    }
  }

  if (owner !== null) {
    const gathered = effectTotals(board, anchor, owner.level);
    const withFactors = gathered.some((one) => one.factor !== 1);
    totals.push(...gathered.map((one) => totalRow(one, withFactors, anchor)));
  }

  html += effectBlock('Total', 'out', true, totals);
  if (owner !== null) html += costBlock(board, anchor);
  return html;
}

/* ------------------------------ the figures ------------------------------

   What a village produces, holds and cost, as the panel beside the board
   shows it. Written once and filled by both pages. */

const NO_RESOURCES = { wood: 0, iron: 0, workers: 0, soldiers: 0 };
const NOT_KNOWN = 'N/A';
const NO_GLOBAL = { production: NO_RESOURCES, storage: NO_RESOURCES };
// Placeholder efficiencies until the engine has replied.
const NO_SIDES = Object.fromEntries(EFFICIENCIES.map((e) => [e.key, 0]));
const NO_EFFECTIVE = { soldiers: NO_SIDES, workers: NO_SIDES };
/* Until the engine has replied, every power is the base the hq is worth, which
   is what an empty village with no modifiers has. */
const NO_POWER = Object.fromEntries(POWERS.map((p) => [p.key, BASE_POWER]));
const NO_UNITS = Object.fromEntries(UNITS.map((u) => [u.key, 0]));
// Until then the market keeps its base share of zero production.
const NO_MARKET = { tax: MARKET_TAX, wood: 0, iron: 0 };

function renderTotals(result) {
  const production = result ? result.production : NO_RESOURCES;
  const storage = result ? result.storage : NO_RESOURCES;
  const unknown = result === null;

  for (const { key } of RESOURCES) {
    document.getElementById(`total-${key}`).textContent = unknown ? NOT_KNOWN : fmt(production[key], 3);
    document.getElementById(`store-${key}`).textContent = unknown ? NOT_KNOWN : fmtStore(storage[key]);
  }

  const global = result ? result.global : NO_GLOBAL;
  for (const kind of ['production', 'storage']) {
    for (const resource of GLOBAL_RESOURCES) {
      const el = document.getElementById(`global-${kind}-${resource}`);
      el.hidden = unknown || !(global[kind][resource] > 0);
      el.textContent = pct(global[kind][resource]);
    }
  }
}

// Built from the engine's list, so a new efficiency needs no edit here.
function buildStatsPanel() {
  const row = (into, key, short, cls, title, start) => {
    const li = document.createElement('li');
    const value = span(`fx-value ${cls}`, start);
    value.id = key;
    value.title = title;
    li.append(span('fx-what', short), value);
    into.append(li);
  };

  const soldiers = document.getElementById('effective-soldiers-list');
  for (const e of SOLDIER_EFFICIENCIES)
    row(soldiers, `effective-soldiers-${e.key}`, e.short, 'soldiers-value', 'Soldiers/t once efficiency is counted', '0');

  const workers = document.getElementById('effective-workers-list');
  for (const e of WORKER_EFFICIENCIES) {
    const short = e.key === 'worker' ? 'age' : e.short;
    row(workers, `effective-workers-${e.key}`, short, 'workers-value',
      e.key === 'worker'
        ? 'Workers/t times worker efficiency'
        : e.key === 'projects'
          ? 'Workers/t times one plus worker efficiency plus projects efficiency'
          : `Workers/t times worker efficiency times ${e.name.toLowerCase()} efficiency`,
      '0');
  }

  const efficiency = document.getElementById('efficiency-list');
  for (const e of EFFICIENCIES)
    row(efficiency, `efficiency-${e.key}`, e.short, 'efficiency-value', `${e.name} efficiency`, '+0%');

  /* Each unit's power, then its production. Support power has no row: both
     power rows already include it. */
  const support = document.getElementById('support-list');
  for (const u of UNITS)
    row(support, `power-${u.key}`, u.short, 'power-value', `${u.one} power, support power included`, fmt(BASE_POWER, 3));
  for (const u of UNITS)
    row(support, `units-${u.key}`, `${u.short}/t`, 'power-value', `${u.name} per tick`, '0');
}

// Derived from the totals rather than summed over the board, and displayed
// under the resource each comes from, so this fills the same panel.
function renderStats(result) {
  const efficiency = result?.efficiency ?? NO_SIDES;
  const effective = result?.effective ?? NO_EFFECTIVE;
  const unknown = result === null;

  for (const { key } of EFFICIENCIES)
    document.getElementById(`efficiency-${key}`).textContent = unknown ? NOT_KNOWN : pct(efficiency[key]);

  const power = result?.power ?? NO_POWER;
  const units = result?.units ?? NO_UNITS;
  for (const { key } of UNITS) {
    document.getElementById(`power-${key}`).textContent = unknown ? NOT_KNOWN : fmt(power[key], 3);
    document.getElementById(`units-${key}`).textContent = unknown ? NOT_KNOWN : fmt(units[key], 3);
  }

  for (const { key } of SOLDIER_EFFICIENCIES)
    document.getElementById(`effective-soldiers-${key}`).textContent = unknown ? NOT_KNOWN : fmt(effective.soldiers[key], 3);

  for (const { key } of WORKER_EFFICIENCIES)
    document.getElementById(`effective-workers-${key}`).textContent = unknown ? NOT_KNOWN : fmt(effective.workers[key], 3);

  // A tax is a share taken rather than added, so it is shown unsigned.
  const market = result?.market ?? NO_MARKET;
  document.getElementById('market-tax').textContent = unknown ? NOT_KNOWN : `${fmt(market.tax * 100, 2)}%`;
  document.getElementById('market-wood').textContent = unknown ? NOT_KNOWN : fmt(market.wood, 3);
  document.getElementById('market-iron').textContent = unknown ? NOT_KNOWN : fmt(market.iron, 3);
}

/* The total cost of every building and its levels. The village's own levels
   are excluded: they buy the village rather than anything standing on it, and
   are shown against the centre instead. */
function renderCosts(result) {
  const total = result?.cost?.total ?? NO_COST;
  const unknown = result === null;

  for (const resource of COSTED) {
    document.getElementById(`cost-${resource}`).textContent
      = unknown ? NOT_KNOWN : fmtStore(total[resource]);
  }
}

/* The stats panel, filled from one engine reply. Both pages show the same
   figures, so both fill it here; `result` is what the engine last returned, or
   null before it has answered. */
function renderStatsPanel(result, modifiers = lastModifiers) {
  lastResult = result;
  lastModifiers = modifiers;
  renderTotals(result);
  renderStats(result);
  renderCosts(result);
  markBreakdownTargets();
  reopenBreakdown();
}

/* --------------------------- how a figure was reached ---------------------

   Clicking a figure in the stats or tile panel opens the terms it was
   computed from. The markup is built here rather than in either page: neither
   knows which figures the engine reports. */

/* The reply and the modifiers it was computed with, for a later click. */
let lastResult = null;
let lastModifiers = {};
let lastBoard = null;
// what is open, so a fresh reply redraws it in place
let openBreakdown = null;

// stats panel element id -> breakdown id; both are built from the same enums
function breakdownIdOf(elementId) {
  const [head, ...rest] = elementId.split('-');
  const tail = rest.join('.');

  if (head === 'total') return `${tail}.${RATE}`;
  if (head === 'store') return `${tail}.${CAPACITY}`;
  if (head === 'efficiency') return `${SCHEMA.efficiencyField}.${tail}`;
  if (head === 'power') return `${tail}.${SCHEMA.powerField}`;
  if (head === 'units') return `${tail}.${SCHEMA.unitField}`;
  if (head === 'market') return `market.${tail}`;
  if (head === 'effective') return `effective.${tail}`;
  return null;
}

// Marks the explainable figures clickable; a cost has no breakdown.
function markBreakdownTargets() {
  for (const el of document.querySelectorAll('.stats .fx-value')) {
    if (el.id === '') continue;
    const id = breakdownIdOf(el.id);
    const explained = id !== null && lastResult !== null && buildBreakdown(id) !== null;

    if (explained) el.dataset.breakdown = id;
    else delete el.dataset.breakdown;
    el.classList.toggle('fx-explained', explained);
  }
}

const BREAKDOWN_KINDS = {
  base: { name: 'base', sign: '' },
  added_before: { name: 'added before', sign: '+' },
  share: { name: 'shares', sign: '+' },
  factor: { name: 'factors', sign: '×' },
  added_after: { name: 'added after', sign: '+' },
};

const BREAKDOWN_ORDER = ['base', 'added_before', 'share', 'factor', 'added_after'];

// neutral: a factor of one, anything else zero
function isNeutralTerm(term) {
  return term.value === (term.kind === 'factor' ? 1 : 0);
}

/* A modifier as the engine was given it: percent entries divided back down,
   then rounded as serialize() writes them. The page's own unrounded value
   would leave the breakdown off by that rounding. */
function modifierWorth(id) {
  const field = MODIFIER_BY_ID.get(id);
  if (field === undefined) return null;

  const entered = modifierIn(lastModifiers, id);
  const value = Number.isFinite(entered) ? entered : field.neutral;
  return Number((field.percent ? value / 100 : value).toFixed(MODIFIER_DECIMALS));
}

function kindOfSource(source) {
  if (source.addedBefore) return 'added_before';
  if (source.addedAfter) return 'added_after';
  return source.share ? 'share' : 'factor';
}

/* One term per modifier source. The resource-only sources are left out of
   the other quantities, where the engine holds them at their neutral. */
function modifierTerms(quantityId, resourceQuantity, prefix = '') {
  const sources = resourceQuantity ? MODIFIER_SOURCES : COMBAT_SOURCES;

  return sources.map((source) => ({
    label: `${prefix}${source.name.toLowerCase()}`,
    value: modifierWorth(`${quantityId}.${source.key}`) ?? (kindOfSource(source) === 'factor' ? 1 : 0),
    kind: kindOfSource(source),
  }));
}

const QUESTS_ID = 'quests';
const BALANCE_ID = 'balance';
const MARKET_TAX_REDUCTION_ID = 'market_tax_reduction';

function questsTerm() {
  return { label: 'quests', value: modifierWorth(QUESTS_ID), kind: 'factor' };
}

// Politics favours one production; the page holds which as the choice's name.
function politicsTerm(resourceKey) {
  const favoured = lastModifiers[SCHEMA.politicsField];
  const worker = resourceKey === 'workers';
  const soldier = resourceKey === 'soldiers';
  const wanted = worker ? 'worker' : (soldier ? 'soldier' : 'resource');

  return { label: 'politics', value: favoured === wanted ? SCHEMA.politicsBonus : 1, kind: 'factor' };
}

/* One figure as its terms, null for an id the page cannot explain. Building
   contributions come from the engine, the modifiers are the page's own; put
   together here, not in the engine, where it would weigh on every search. */
function buildBreakdown(id) {
  const from = lastResult?.fromBuildings;
  if (from === undefined) return null;

  const base = (of) => ({ label: 'buildings', value: from.base[of] ?? 0, kind: 'base' });
  const buildingShare = (of) => ({ label: 'buildings', value: from.shares[of] ?? 0, kind: 'share' });
  const buildingFactor = (of) => ({ label: 'buildings', value: from.factors[of] ?? 1, kind: 'factor' });

  const parts = id.split('.');

  // a resource, per tick or as a capacity
  if (RESOURCES.some((r) => r.key === parts[0]) && (parts[1] === RATE || parts[1] === CAPACITY) && parts.length === 2) {
    const perTick = parts[1] === RATE;
    const terms = [base(id)];
    if (!perTick) terms.push({ label: 'village base', value: BASE_STORAGE[parts[0]], kind: 'added_before' });
    terms.push(buildingShare(id), buildingFactor(id), ...modifierTerms(id, true), questsTerm());
    if (perTick) {
      terms.push({ label: 'balance', value: modifierWorth(BALANCE_ID), kind: 'factor' });
      terms.push(politicsTerm(parts[0]));
    }
    return { total: lastResult[perTick ? 'production' : 'storage'][parts[0]], terms };
  }

  // an efficiency, reported as the bonus over the 1 it starts from
  if (parts[0] === SCHEMA.efficiencyField && parts.length === 2) {
    const efficiency = EFFICIENCIES.find((e) => e.key === parts[1]);
    if (efficiency === undefined) return null;

    const terms = [{ label: 'base', value: 1, kind: 'base' }, buildingShare(id), ...modifierTerms(id, false)];
    if (efficiency.quests) terms.push(questsTerm());
    terms.push({ label: 'to bonus', value: -1, kind: 'added_after' });
    return { total: lastResult.efficiency[parts[1]], terms };
  }

  /* A power, from the hq's base. Support power feeds knight and guardian
     power alike, so its terms appear in both, named apart. */
  if (parts[1] === SCHEMA.powerField && parts.length === 2) {
    const support = `support.${SCHEMA.powerField}`;
    const terms = [
      { label: 'base', value: BASE_POWER, kind: 'base' },
      buildingShare(id),
      ...modifierTerms(id, false),
    ];
    if (parts[0] !== 'support') {
      terms.push({ label: 'support buildings', value: from.shares[support] ?? 0, kind: 'share' });
      terms.push(...modifierTerms(support, false, 'support '));
    }
    terms.push(questsTerm());
    return { total: lastResult.power[parts[0]], terms };
  }

  // a unit's production; same id shape as a resource, so tested after them
  if (UNITS.some((u) => u.key === parts[0]) && parts[1] === SCHEMA.unitField && parts.length === 2) {
    return {
      total: lastResult.units[parts[0]],
      terms: [base(id), buildingShare(id), buildingFactor(id), ...modifierTerms(id, false), questsTerm()],
    };
  }

  // No modifier scales the tax: reductions are subtracted, clamped at zero.
  if (id === 'market.tax') {
    const unclamped = from.base['market.tax'] + (from.shares['market.tax'] ?? 0) - modifierWorth(MARKET_TAX_REDUCTION_ID);
    return {
      total: lastResult.market.tax,
      terms: [
        { label: 'base', value: from.base['market.tax'], kind: 'base' },
        { label: 'perk', value: -modifierWorth(MARKET_TAX_REDUCTION_ID), kind: 'added_before' },
        { label: 'buildings', value: from.shares['market.tax'] ?? 0, kind: 'added_before' },
        { label: 'clamp to 0', value: lastResult.market.tax - unclamped, kind: 'added_after' },
      ],
    };
  }

  // production left after the market's cut
  if (parts[0] === 'market' && (parts[1] === 'wood' || parts[1] === 'iron')) {
    return {
      total: lastResult.market[parts[1]],
      terms: [
        { label: `${parts[1]}/t`, value: lastResult.production[parts[1]], kind: 'base', from: `${parts[1]}.${RATE}` },
        { label: '1 - tax', value: 1 - lastResult.market.tax, kind: 'factor', from: 'market.tax' },
      ],
    };
  }

  /* production scaled by its efficiencies; worker efficiency feeds all three,
     with project efficiency summed with it and map efficiency multiplying on
     top of it */
  if (parts[0] === 'effective' && parts.length === 3) {
    const [, which, key] = parts;
    const efficiencyId = (of) => `${SCHEMA.efficiencyField}.${of}`;
    const resource = which === 'soldiers' ? 'soldiers' : 'workers';

    const terms = [{
      label: `${resource}/t`, value: lastResult.production[resource], kind: 'base', from: `${resource}.${RATE}`,
    }];
    const scaledBy = (of, kind) => ({
      label: `${of} efficiency`, value: kind === 'share' ? lastResult.efficiency[of] : 1 + lastResult.efficiency[of], kind, from: efficiencyId(of),
    });

    if (which !== 'workers') {
      terms.push(scaledBy(key, 'factor'));
    } else if (key === 'projects') {
      terms.push(scaledBy('worker', 'share'), scaledBy('projects', 'share'));
    } else {
      terms.push(scaledBy('worker', 'factor'));
      if (key !== 'worker') terms.push(scaledBy(key, 'factor'));
    }
    return { total: lastResult.effective[which][key], terms };
  }

  return null;
}

// The terms folded in the engine's order, as the value after each stage.
function breakdownStages(terms) {
  const sum = (kind) => terms.filter((t) => t.kind === kind).reduce((total, t) => total + t.value, 0);
  const product = (kind) => terms.filter((t) => t.kind === kind).reduce((total, t) => total * t.value, 1);

  const base = sum('base') + sum('added_before');

  return {
    base,
    shares: 1 + sum('share'),
    factors: product('factor'),
    after: sum('added_after'),
  };
}

/* How many times an effect's condition is met: once for a base effect, once
   per covered tile of its terrain, once per adjacent building it names (a
   neighbour touching at several tiles counted once). */
function effectReach(board, cells, beside, effect) {
  if (effect.where === 'base') return 1;
  if (effect.where === 'terrain') {
    return effect.on.reduce((scale, ground) => scale + terrainScale(board, cells, ground), 0);
  }
  if (effect.where === 'adjacent') return beside.filter((b) => effect.on.includes(b)).length;
  return 0; // an aura applies to the neighbours, not to this tile
}

// The perk's part of a terrain effect's reach, apart from the tiles matched.
function effectGround(board, cells, effect) {
  if (effect.where !== 'terrain') return 1;

  const matching = cells.filter((cell) => effect.on.includes(board.tiles[cell].terrain)).length;
  if (matching === 0) return 1;
  return effectReach(board, cells, [], effect) / matching;
}

// what resolveRateOrCapacity does: a quantity naming neither is a rate
function rateOrCapacityOf(effect) {
  return effect.rateOrCapacity === CAPACITY ? CAPACITY : RATE;
}

// The panel's name for an effect's condition, with how often it was met.
function effectSource(effect, times) {
  if (effect.where === 'base') return 'base';

  const named = effect.where === 'terrain'
    ? effect.on.map((one) => (TERRAIN_BY_KEY.get(one)?.name ?? one).toLowerCase()).join('/')
    : effect.on.map((one) => (BUILDING_BY_KEY.get(one)?.name ?? one).toLowerCase()).join('/');

  return times > 1 ? `${named} ×${times}` : named;
}

// Terms rewritten so a list of them reads back as one figure.
function asSum(terms) {
  return terms.map((term) => ({ ...term, kind: 'base' }));
}

function asProduct(terms) {
  if (terms.length === 0) return [{ label: 'base', value: 1, kind: 'base' }];
  return [{ ...terms[0], kind: 'base' }, ...terms.slice(1).map((term) => ({ ...term, kind: 'factor' }))];
}

/* What scales one effect on one tile: level, the master builder's seal over
   that level, times met, and the mill or barrel seal unless shown apart. A
   terrain effect's times met carries `ground`, split back out as its own. */
function effectScaling(effect, owner, times, effects, sealShownApart, ground = 1) {
  const parts = [];
  if (effect.perLevel) {
    parts.push({ label: 'level', value: owner.level, kind: 'factor' });
    if (owner.seal === 'LEVEL_BOOST') {
      parts.push({ label: SEAL_BY_KEY.get('LEVEL_BOOST')?.name ?? 'LEVEL_BOOST', value: MASTER_LEVEL_BONUS, kind: 'factor' });
    }
  }
  if (times / ground !== 1) parts.push({ label: 'times met', value: times / ground, kind: 'factor' });
  if (ground !== 1) parts.push({ label: FERTILE_GROUNDS.toLowerCase(), value: ground, kind: 'factor' });
  if (!sealShownApart && sealScales(effect, owner.seal, effects)) {
    parts.push({ label: SEAL_BY_KEY.get(owner.seal)?.name ?? owner.seal, value: SEAL_BONUS, kind: 'factor' });
  }
  return parts;
}

/* One effect as a term, with what scales it in `parts`. A factor is scaled
   as what it adds above one, so its parts take the one off and put it back.

   sealShownApart: the caller shows the mill or barrel seal over the whole
   figure, as a building with an output of its own does. */
function effectTerm(effect, owner, times, label, effects = [], sealShownApart = false, ground = 1) {
  const scale = sealShownApart
    ? times * (effect.perLevel ? owner.level * (owner.seal === 'LEVEL_BOOST' ? MASTER_LEVEL_BONUS : 1) : 1)
    : effectTimes(effect, owner.level, owner.seal, times, effects);
  const scaling = effectScaling(effect, owner, times, effects, sealShownApart, ground);

  if (effect.amount !== 'multiply') {
    return {
      label,
      value: effect.value * scale,
      kind: effect.amount === 'flat' ? 'base' : 'share',
      parts: [{ label: effect.perLevel ? 'per level' : 'flat', value: effect.value, kind: 'base' }, ...scaling],
    };
  }

  /* A terrain factor compounds, once per matching tile; every other is
     applied once over the times met. Only the latter reads back as a chain. */
  if (effect.where === 'terrain' && times / ground > 1) {
    const tiles = times / ground;
    return { label, value: (1 + (effect.value - 1) * (scale / tiles)) ** tiles, kind: 'factor' };
  }

  return {
    label,
    value: 1 + (effect.value - 1) * scale,
    kind: 'factor',
    parts: [
      { label: effect.perLevel ? 'per level' : 'flat', value: effect.value, kind: 'base' },
      { label: 'to share', value: -1, kind: 'added_before' },
      ...scaling,
      { label: 'to factor', value: 1, kind: 'added_after' },
    ],
  };
}

/* One term per effect feeding one quantity on one tile, in the engine's
   shape: flat amounts the base, shares summed over it, factors multiplying
   that. The rate or capacity seal is a factor of its own rather than folded
   into each flat amount, which comes to the same. */
function tileOwnTerms(anchor, quantity, rateOrCapacity) {
  const owner = lastBoard?.tiles?.[anchor];
  if (owner === undefined) return null;

  const cells = footprintCells(anchor, owner.building, owner.orientation) ?? [anchor];
  const beside = buildingsBeside(lastBoard, anchor, cells);
  const effects = (effectsByBuilding.get(owner.building) ?? [])
    .filter((e) => e.quantity === quantity && rateOrCapacityOf(e) === rateOrCapacity && e.where !== 'provides');

  const terms = [];
  for (const effect of effects) {
    const times = effectReach(lastBoard, cells, beside, effect);
    if (times === 0) continue;

    const ground = effectGround(lastBoard, cells, effect);
    terms.push(effectTerm(effect, owner, times, effectSource(effect, times / ground), effects, true, ground));
  }

  for (const aura of aurasMultiplying(lastBoard, cells, quantity, rateOrCapacity)) {
    terms.push({ label: `${BUILDING_BY_KEY.get(aura.from)?.name ?? aura.from} aura`, value: aura.value, kind: 'factor' });
  }

  if (owner.seal === SEAL_FOR_RATE_OR_CAPACITY[rateOrCapacity] && GLOBAL_RESOURCES.includes(quantity)) {
    terms.push({ label: SEAL_BY_KEY.get(owner.seal)?.name ?? owner.seal, value: SEAL_BONUS, kind: 'factor' });
  }

  return terms;
}

/* The same figure for one tile: the building's own worth, then the
   village-wide shares and factors. What is added to the village's base or
   total belongs to no tile and is dropped.

   Fallback where the tile's effects cannot be read back: the engine's tile
   figure divided by the village multiplier. */
function tileBreakdown(breakdown, resourceKey, rateOrCapacity, tileIndex) {
  const own = lastResult.tiles[rateOrCapacity][resourceKey][tileIndex];
  const scaling = breakdown.terms.filter((t) => t.kind === 'share' || t.kind === 'factor');
  const anchor = lastBoard === null ? null : occupancyMap(lastBoard.tiles)[tileIndex];
  const mine = anchor === null ? null : tileOwnTerms(anchor, resourceKey, rateOrCapacity);

  if (mine === null || mine.length === 0) {
    const stages = breakdownStages(scaling);
    return {
      total: own,
      terms: [{ label: 'this tile', value: own / (stages.shares * stages.factors), kind: 'base' }, ...scaling],
    };
  }

  return { total: own, terms: [...mine, ...scaling] };
}

let breakdownModal = null;

function buildBreakdownModal() {
  if (breakdownModal !== null) return breakdownModal;

  breakdownModal = document.createElement('div');
  breakdownModal.className = 'modal breakdown-modal';
  breakdownModal.hidden = true;
  breakdownModal.innerHTML = '<div class="modal-backdrop" data-close-breakdown></div>'
    + '<div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="breakdown-title">'
    + '<div class="modal-head"><h2 id="breakdown-title"></h2>'
    + '<button type="button" class="modal-close" data-close-breakdown title="Close (Esc)">&#10005;</button></div>'
    + '<div class="breakdown-body"></div>'
    + '<p class="breakdown-foot"><label><input type="checkbox" id="breakdown-all">'
    + ' show neutral terms</label></p></div>';
  document.body.append(breakdownModal);

  breakdownModal.querySelectorAll('[data-close-breakdown]').forEach((el) => {
    el.addEventListener('click', hideBreakdown);
  });
  breakdownModal.querySelector('#breakdown-all').addEventListener('change', () => {
    reopenBreakdown();
  });

  return breakdownModal;
}

// The panel's name for a figure; the ids are enum paths, not names.
function breakdownName(id, tileIndex) {
  const [first, second, third] = id.split('.');

  const named = first === SCHEMA.efficiencyField ? `${second} efficiency`
    : first === 'effective' ? `${second}/t ${third === 'projects' ? '+' : '×'} ${third} efficiency`
      : first === 'market' ? (second === 'tax' ? 'market tax' : `${second} sold`)
        : second === SCHEMA.powerField ? `${first} power`
          : second === CAPACITY ? `${first} cap`
            : `${first}/t`;

  return tileIndex === null ? named : `${named} @ ${tileIndex % WIDTH},${Math.floor(tileIndex / WIDTH)}`;
}

// Open terms by path, so a redraw leaves the panel as it was left.
const expandedTerms = new Set();

/* One row per term, grouped by the part it plays. A term made of others
   carries them in `parts`, which open into a block under it. Headings only at
   the top level: inside a block the signs carry the same meaning. */
function breakdownRows(terms, showAll, path = '', depth = 0) {
  let html = '';

  for (const kind of BREAKDOWN_ORDER) {
    const shown = terms
      .map((term, at) => ({ term, at }))
      .filter(({ term }) => term.kind === kind && (showAll || !isNeutralTerm(term)));
    if (shown.length === 0) continue;

    if (depth === 0) html += `<li class="fx-cols"><span class="fx-what">${BREAKDOWN_KINDS[kind].name}</span></li>`;

    for (const { term, at } of shown) {
      // An added term carries its own sign, so a negative one drops the plus.
      const added = BREAKDOWN_KINDS[kind].sign === '+';
      const value = added
        ? `${term.value < 0 ? '-' : '+'}${fmt(Math.abs(term.value), 4)}`
        : `${BREAKDOWN_KINDS[kind].sign}${fmt(term.value, 4)}`;

      const here = `${path}/${at}`;
      const parts = term.parts ?? [];
      const open = expandedTerms.has(here);

      const label = parts.length > 0
        ? `<button type="button" class="breakdown-expand" data-expand="${here}">`
          + `<span class="breakdown-caret">${open ? '▾' : '▸'}</span>${term.label}</button>`
        : (term.from
          ? `<button type="button" class="breakdown-link" data-breakdown="${term.from}">${term.label}</button>`
          : term.label);

      const marks = (isNeutralTerm(term) ? ' breakdown-nil' : '') + (open ? ' breakdown-open' : '');
      html += `<li class="${marks.trim()}">`
        + `<span class="fx-what">${label}</span>`
        + `<span class="fx-value ${kind === 'factor' ? 'fx-times' : 'fx-plus'}">${value}</span></li>`;

      if (open) {
        html += '<li class="breakdown-parts"><ul class="fx-list breakdown-terms">'
          + breakdownRows(parts, showAll, here, depth + 1) + '</ul></li>';
      }
    }
  }

  return html;
}

/* The steps and what they come to. For an engine-reported figure this is a
   check: the terms are the page's, so agreement means it accounts for
   everything the engine applied. */
function breakdownSum(terms, total) {
  const stages = breakdownStages(terms);
  const steps = [`${fmt(stages.base, 4)}`];
  if (stages.shares !== 1) steps.push(`× ${fmt(stages.shares, 4)}`);
  if (stages.factors !== 1) steps.push(`× ${fmt(stages.factors, 4)}`);
  if (stages.after !== 0) steps.push(`${stages.after > 0 ? '+' : '-'} ${fmt(Math.abs(stages.after), 4)}`);

  const reached = stages.base * stages.shares * stages.factors + stages.after;
  return {
    reached,
    agrees: Math.abs(reached - total) <= 1e-6 * Math.max(1, Math.abs(total)),
    html: `${steps.join(' ')} = <b>${fmt(total, 4)}</b>`,
  };
}

/* The panel: a title and one chain per figure. A row carrying both a share
   and a factor gets a chain for each, the two reaching the village's
   arithmetic by different routes. A chain that does not come to the engine's
   figure is flagged: the fault is the panel's. */
function showChains(title, chains) {
  const modal = buildBreakdownModal();
  const showAll = modal.querySelector('#breakdown-all').checked;

  modal.querySelector('#breakdown-title').textContent = title;
  modal.querySelector('.breakdown-body').innerHTML = chains.map((chain) => {
    const sum = breakdownSum(chain.terms, chain.total);

    return (chain.heading === undefined ? '' : `<h3 class="breakdown-heading">${chain.heading}</h3>`)
      + `<p class="breakdown-sum${sum.agrees ? '' : ' breakdown-off'}">${sum.html}</p>`
      + (sum.agrees ? '' : `<p class="breakdown-warning">steps give ${fmt(sum.reached, 4)}, engine reports ${fmt(chain.total, 4)}</p>`)
      + `<ul class="fx-list breakdown-terms">${breakdownRows(chain.terms, showAll)}</ul>`;
  }).join('');

  modal.hidden = false;
}

// tileIndex narrows a resource to one tile's share, as the tile panel shows.
function showBreakdown(id, tileIndex = null) {
  const found = buildBreakdown(id);
  if (found === null) return;

  // only the resources are reported per tile
  const [resourceKey, rateOrCapacity] = id.split('.');
  const perTile = lastResult.tiles?.[rateOrCapacity]?.[resourceKey];
  const explained = tileIndex === null || perTile === undefined
    ? found
    : tileBreakdown(found, resourceKey, rateOrCapacity, tileIndex);
  const narrowed = explained === found ? null : tileIndex;

  openBreakdown = { figure: id, tile: narrowed };
  showChains(breakdownName(id, narrowed), [explained]);
}

/* What one tile contributes to the village's arithmetic rather than to its
   own output: the shares and factors the stats panel shows only summed. */
function tileTotalChains(anchor, quantity, rateOrCapacity) {
  const owner = lastBoard?.tiles?.[anchor];
  if (owner === undefined) return null;

  const row = effectTotals(lastBoard, anchor, owner.level)
    .find((one) => one.quantity === quantity && one.rateOrCapacity === rateOrCapacity);
  if (row === undefined) return null;

  const named = BUILDING_BY_KEY.get(owner.building)?.name ?? owner.building;
  const auraTerms = row.auras.map((aura) => ({
    label: `${BUILDING_BY_KEY.get(aura.from)?.name ?? aura.from} aura`,
    value: aura.value,
    kind: 'factor',
  }));

  const onTile = effectsByBuilding.get(owner.building) ?? [];
  const fed = row.from.map(({ effect, times, ground }) => effectTerm(
    effect, owner, times, effectSource(effect, times / ground), onTile, false, ground,
  ));
  const shares = fed.filter((term) => term.kind === 'share');
  const factors = fed.filter((term) => term.kind === 'factor');

  const chains = [];
  if (row.share !== 0) {
    chains.push({
      heading: row.factor === 1 ? undefined : 'share',
      total: row.share,
      terms: [
        { label: `${named} lvl ${owner.level}`, value: row.perLevelShare, kind: 'base', parts: asSum(shares) },
        ...auraTerms,
        // a flat share is village-wide outright: nothing on this tile scales it
        { label: 'flat share', value: row.flatShare, kind: 'added_after' },
      ],
    });
  }
  // A factor reaches the village as what it adds above one, which is what auras multiply.
  if (row.factor !== 1) {
    chains.push({
      heading: row.share === 0 ? undefined : 'factor',
      total: row.factor,
      terms: [
        { label: `${named} lvl ${owner.level}`, value: row.ownFactor, kind: 'base', parts: asProduct(factors) },
        { label: 'to share', value: -1, kind: 'added_before' },
        ...auraTerms,
        { label: 'to factor', value: 1, kind: 'added_after' },
      ],
    });
  }

  return { title: `${effectLabel(row)} · ${named} @ ${anchor % WIDTH},${Math.floor(anchor / WIDTH)}`, chains };
}

function showTileTotal(anchor, quantity, rateOrCapacity) {
  const found = tileTotalChains(anchor, quantity, rateOrCapacity);
  if (found === null) return;

  openBreakdown = { tileTotal: { anchor, quantity, rateOrCapacity } };
  showChains(found.title, found.chains);
}

// What one aura a building provides comes to.
function showTileAura(anchor, nth) {
  const owner = lastBoard?.tiles?.[anchor];
  if (owner === undefined) return;

  const effects = effectsByBuilding.get(owner.building) ?? [];
  const effect = effects.filter((e) => e.where === 'provides')[nth];
  if (effect === undefined) return;

  const cells = footprintCells(anchor, owner.building, owner.orientation) ?? [anchor];
  const level = owner.level; // the centre's tile level is kept at the village's
  const times = effectTimes(effect, level, owner.seal, 1, effects);
  const named = BUILDING_BY_KEY.get(owner.building)?.name ?? owner.building;

  // A factor reaches neighbours as what it adds above one; a share already is.
  const terms = effect.amount === 'multiply'
    ? [
      { label: `${named} lvl ${level}`, value: 1 + (effect.value - 1) * times, kind: 'base' },
      { label: 'to share', value: -1, kind: 'added_before' },
      { label: 'to factor', value: 1, kind: 'added_after' },
    ]
    : [{ label: `${named} lvl ${level}`, value: effect.value * times, kind: 'base' }];

  const total = effect.amount === 'multiply'
    ? 1 + (effect.value - 1) * times
    : effect.value * times;

  openBreakdown = { tileAura: { anchor, nth } };
  showChains(`${effectLabel(effect)} aura · ${named} @ ${anchor % WIDTH},${Math.floor(anchor / WIDTH)}`, [{ total, terms }]);
}

// redraws whatever is open, after a reply or a change of board
function reopenBreakdown() {
  if (openBreakdown === null) return;
  if (openBreakdown.figure !== undefined) showBreakdown(openBreakdown.figure, openBreakdown.tile);
  else if (openBreakdown.tileAura !== undefined) showTileAura(openBreakdown.tileAura.anchor, openBreakdown.tileAura.nth);
  else showTileTotal(openBreakdown.tileTotal.anchor, openBreakdown.tileTotal.quantity, openBreakdown.tileTotal.rateOrCapacity);
}

function hideBreakdown() {
  if (breakdownModal !== null) breakdownModal.hidden = true;
  openBreakdown = null;
}

// One listener for every figure: both panels are rebuilt constantly.
document.addEventListener('click', (event) => {
  const expand = event.target.closest('[data-expand]');
  if (expand !== null) {
    event.preventDefault();
    const at = expand.dataset.expand;
    if (expandedTerms.has(at)) expandedTerms.delete(at);
    else expandedTerms.add(at);
    reopenBreakdown();
    return;
  }

  const aura = event.target.closest('[data-tile-aura]');
  if (aura !== null) {
    event.preventDefault();
    const [anchor, nth] = aura.dataset.tileAura.split('|');
    showTileAura(Number(anchor), Number(nth));
    return;
  }

  const row = event.target.closest('[data-tile-total]');
  if (row !== null) {
    event.preventDefault();
    const [anchor, quantity, rateOrCapacity] = row.dataset.tileTotal.split('|');
    showTileTotal(Number(anchor), quantity, rateOrCapacity);
    return;
  }

  const target = event.target.closest('[data-breakdown]');
  if (target === null) return;

  event.preventDefault();
  const tile = target.dataset.tile;
  showBreakdown(target.dataset.breakdown, tile === undefined ? null : Number(tile));
});

document.addEventListener('keydown', (event) => {
  if (event.key === 'Escape' && breakdownModal !== null && !breakdownModal.hidden) {
    event.stopPropagation();
    hideBreakdown();
  }
}, true);
